### ISSUE TITLE
Reference to same table

### ISSUE THREAD

**Issue by d-winter** [calebmer/postgraphql#101]
Hi,
i have a table with a foreign key pointing to the same table.
The created GraphQL schema only points to the integer, not to the linked entity.
Is the expected behaviour? I thought I could query a new node with this setting.
Thanks in advance
Daniel

**Comment by calebmer** [comment]
Yeah this should work, could I see your PostgreSQL schema?

**Comment by d-winter** [comment]
Hey, @calebmer  
here is the create script.
```
   CREATE TABLE p201fbd61724d2da760c1f01."favorites-positions"
   (
       id integer NOT NULL DEFAULT nextval('p201fbd61724d2da760c1f01."favorites-      positions_id_seq"'::regclass),

    longtext text COLLATE "default".pg_catalog,

    "refToSelf" integer,

    booleanfield boolean,

    CONSTRAINT "favorites-positions_pkey" PRIMARY KEY (id),
    
    CONSTRAINT "favorites-positions_refToSelf_fkey" FOREIGN KEY ("refToSelf")
        REFERENCES p201fbd61724d2da760c1f01."favorites-positions" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION

)
WITH (
    OIDS = FALSE
)
```

**Comment by d-winter** [comment]
Oh, got it. There are two fields to query in GraphQL. One returns the int value, one the node.
Sorry for my mistake and thanks a ton for this project!

**Comment by calebmer** [comment]
👍
