### ISSUE TITLE
Would it be better if dates used ISO8601?

### ISSUE THREAD

**Issue by benjie** [calebmer/postgraphql#107]
In types.js, [dates are serialized using `String(...)`](https://github.com/calebmer/postgraphql/blob/9d062b11cb687504561e51e8e7bfd201dcf5223a/src/graphql/types.js#L112-L115); however it's more convenient to deal with dates in ISO8601 format. I understand JavaScript's native `toISOString` strips the timezone information, so it's not suitable. However, an ISO8601-compliant date formatter could be implemented in a few lines of code using [`getTimezoneOffset()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset). Would you be open to a pull request to change the date format? (It's a breaking change, so maybe this is something to put in version 2?)

**Comment by calebmer** [comment]
Yep, open a PR so I can see how you'd like it. To note, I'm just using the native PostgreSQL format so also check out [`pg-types`](https://www.npmjs.com/package/pg-types). In the meantime you can use `pg-types` parser override mechanism to transform dates into whatever form you want and that should flow through PostGraphQL 👍

**Comment by calebmer** [comment]
Another option, which may be better is we turn date types into objects. That way we can expose fields for `minutes`, `hours`, and `seconds` as well as exposing fields for popular formats like `iso` and utility fields like `lessThen`, `delta`, etc. This may be less ergonomic, but has some interesting upsides. What do you think?

**Comment by langpavel** [comment]
Another variant acceptable for me is javascript timestamp, represented by number in millis in similar way as UNIX timestamp..
If this can be configurable it will be awesome

**Comment by benjie** [comment]
I like the idea of making a few of these formats available, e.g.:

```js
const thing = {
  title: "My Thing",
  myDate: {
    iso: date.toISOString(),
    unix: +date/1000,
    string: moment(iso).format(),
    timezone: date.getTimezoneOffset(),
    hours: date.getHours(),
    utcHours: date.getUTCHours(),
    ...
  }
}
```

but I'm not sure how well this meshes with a mutation to update it `UpdateThing(myThing.rowId, {newTitle: "This Thing Is My Thing", newMyDate: newDate})`. I also think doing this may be over-reaching - chances are the user's going to have to implement some custom logic of the top of this anyway; maybe it's better to just do an ISO8601 with timezone string and let the user worry about formatting it.

**Comment by calebmer** [comment]
Good point about updating. If we wanted though we could accept an ISO string and a unix timestamp integer when updating and switch on type (of course that wouldn’t be available in output).

Also, a super quick Google Search finds [this SO answer recommending ISO 8601](http://stackoverflow.com/questions/3558458/recommended-date-format-for-rest-api#3558614), so I’m down with it.

**Comment by benjie** [comment]
Heh, I should have posted this earlier:

https://xkcd.com/1179/

![ISO8601](http://imgs.xkcd.com/comics/iso_8601.png)

**Comment by calebmer** [comment]
I’m going to close this as its in the PostGraphQL 2.0 beta 🎉 

Start playing with the pre-release, the final release should be out really soon. Tell me what you think! :+1:

```
npm install -g postgraphql@next
postgraphql
```
