### ISSUE TITLE
Mutation Payloads and Relations

### ISSUE THREAD

**Issue by tim-field** [calebmer/postgraphql#114]
Lets say I have a comment table related to my posts table.

```
Post {
  commentNodesByPostId
}
```

And my post page uses `commentNodesByPostId` to show a list of comments.
I want to add a comment, so in another component I call the generated;

`insertComment` mutation

The problem I'm having is that payload of this mutation doesn't include the post that I'm related to, and because of this I haven't been able to work out how to get Relay to correctly update it's local store.  

Relay's `RANGE_ADD` seems to need `post` in the top level of the mutation payload in order to work. If it did I could follow along with this example;

https://facebook.github.io/relay/docs/guides-mutations.html#range-add-example

And have a fatQuery that looked like;

```
fragment on InsertCommentPayload {
        post { commentNodesByPostId },
        commentEdge,
}
```

Without `post` in the payload I can't get Relay to update correctly ( I can't find an incarnation of `FIELDS_CHANGE` to force the correct update either ) 

I imagine this is really common use case, how are people getting around this?

**Comment by calebmer** [comment]
Yeah, a similar issue is this https://github.com/calebmer/postgraphql/issues/110 and this keeps popping up from time to time in the chatroom. I’m not sure of a good way to fix this (short of praying Relay 2 gets released quickly :wink:), I’d like to hear if other people have found workarounds.

I think what we’ll need to do is just flatten out some of the fields of the return type unfortunately. I don’t like having to do that, but I agree that might be the best/only way to make Relay happy.

If anyone is interested in writing a proposal, I’ll see what I can do to implement it :+1:

**Comment by tim-field** [comment]
> I think what we’ll need to do is just flatten out some of the fields of the return type unfortunately

Yes this seems to be what's needed. Could we do this for all foreign key fields in the table being mutated. How difficult would this be? If you don't have time could you point me in the general direction in the code base.

**Comment by calebmer** [comment]
The fields would be defined in the [`createInsertMutationField`’s](https://github.com/calebmer/postgraphql/blob/b443473f15b4c36a6f378b204172ed5676703d7f/src/graphql/mutation/createInsertMutationField.js#L62) payload. It should probably be as easy as taking a GraphQL field off of the type returned by [`createTableType(table)`](https://github.com/calebmer/postgraphql/blob/b443473f15b4c36a6f378b204172ed5676703d7f/src/graphql/mutation/createInsertMutationField.js#L64) and adding them to the payload. So something like:

```js
fields: {
  [table.getFieldName()]: {
    type: tableType,
    description: `The inserted ${table.getMarkdownTypeName()}.`,
    resolve: ({ output }) => output,
  },

  post: tableType.getFields().commentNodesByPostId,
  …
```

You might also need to wrap `resolve` though.

**Comment by ferdinandsalis** [comment]
I cam a across the same problem and have yet to find a way around i :) Will let you know if I do.

**Comment by tim-field** [comment]
Ok so we _just_ need this bit `post: tableType.getFields().commentNodesByPostId` to be automatic for all foreign keys in the table.  With this in place Relay mutations will be much easier!

**Comment by calebmer** [comment]
I’m going to close this as its in the PostGraphQL 2.0 beta 🎉 

Specifically, all related tables are including in create mutations, update mutations, delete mutations, and procedure mutations that return a table.

Start playing with the pre-release, the final release should be out really soon. Tell me what you think! :+1:

```
npm install -g postgraphql@next
postgraphql
```
