### ISSUE TITLE
False boolean values always null

### ISSUE THREAD

**Issue by d-winter** [calebmer/postgraphql#116]
Hi,
when inserting a boolean field in a mutation with the value false results in the value null.

![screen shot 2016-09-20 at 13 44 52](https://cloud.githubusercontent.com/assets/11208517/18668924/a8d75f26-7f38-11e6-8927-d5d753f8492a.png)
Querying for records with false boolean values results also to null.
Is this a bug? I am using 1.9.2.

Another thing is the serialization of JSON. When I request json from the client, I only get "[object Object]", not the serialized JSON as a string. Thought this should be the correct behaviour?
Thanks in advance!
Daniel

**Comment by calebmer** [comment]
Might be related to https://github.com/calebmer/postgraphql/issues/108, I’ll definetly explore.

**Comment by calebmer** [comment]
As for JSON, yeah that’s a bug. Look at https://github.com/calebmer/postgraphql/pull/102 though for more conversation on how we should handle the `JSON` type.

**Comment by calebmer** [comment]
There’s a PR in now for the false bug, just waiting for a review and I’ll release :+1: https://github.com/calebmer/postgraphql/pull/120

**Comment by calebmer** [comment]
There’s also now a PR for JSON type serialization https://github.com/calebmer/postgraphql/pull/121

**Comment by calebmer** [comment]
Fix is in `1.9.3` :tada:
