### ISSUE TITLE
Rationale of using "new" prefix in mutation input

### ISSUE THREAD

**Issue by ivosabev** [calebmer/postgraphql#125]
I do not understand the reasoning behind prefixing the fields with "new" inside the `UpdateInput` object. I haven't seen such behavior in any Relay app and I think it makes unnecessary assumptions about the input data.

I think most of the people will have their objects both during insert and update in a object with keys based on the table columns, rather then prefixing them with "new" in during an update.

Of course it might be a matter of style, but I think that the simplest thing will be not to make any assumptions if the user will prefix his own object with "new" and just go with the plain column names as in the `InsertInput`.

**Comment by calebmer** [comment]
Yep, the rationale was because we also need keyspace for the row identifier. So for example if you had a primary key on `person_id` and `post_id` for example, you may have an input type of:

```graphql
type UpdateInput {
  personId: String
  postId: String
  newPersonId: String
  newPostId: String
  newTimestamp: Number
}
```

What other options do you see? Perhaps a:

```graphql
type UpdateInput {
  personId: String
  postId: String
  patch: UpdateInputPatch
}

type UpdateInputPatch {
  personId: String
  postId: String
  timestamp: Number
}
```

Any other ideas are welcome :+1:

**Comment by ivosabev** [comment]
If we use the global ID as a primary source of truth this would be unnecessary as the global ID is recalculated on the server only after the `personId` and `postId` are updated.

So you can safely do this and pass the new values for the `personId` and `postId`, and the old value for `id` as this will be the only one available until the server returns the new calculation.

```
type UpdateInput {
  id: ID
  personId: String
  postId: String  
  timestamp: Number
}
```

**Comment by calebmer** [comment]
I’m going to close this as its in the PostGraphQL 2.0 beta (#145) 🎉 

We are going with the patch approach like I mentioned, but we are also allowing you to perform mutations using the global id like you mention. Because I agree it should be the one source of truth :blush:

Start playing with the pre-release, the final release should be out really soon. Tell me what you think! :+1:

```
npm install -g postgraphql@next
postgraphql
```
