### ISSUE TITLE
Support mutations by global ID

### ISSUE THREAD

**Issue by ivosabev** [calebmer/postgraphql#126]
I think **postgrahql** should support the global `id` in mutations, since in Relay this is the primary source of identifying an object and here `rowId` is only provided as a convenience.

```
mutation updateTeam($input: UpdateTeamInput!) {
  updateTeam(input: $input) {
    team {
      id,
      name
    }
  }
}

{
  "input": {
    "id":"dGVhbTox",
    "newName": "My Team"
  }
}
```

**Comment by calebmer** [comment]
Yep, this is definitely something that will be in PostGraphQL 2 :blush:. Also being able to insert/update/delete by any unique constraint as well similar to how you can select by any unique constraint.

The one difficulty around this is how do we support procedures? For mutations I’m fine with an `updateTeam`, `updateTeamByRowId`, `updateTeamByUniqueColumn` etc. However, for procedures that take a row as an argument do we make extra copies of that as well? To illustrate the problem, say we have a procedure and it’s a mutation:

```sql
create function do_stuff(person person, i integer) returns person …
```

What would our GraphQL mutations look like?

```graphql
type Mutation {
  doStuff(personId: ID, i: Int): DoStuffPayload
  doStuffByRowId(personRowId: ID, i: Int): DoStuffPayload
  doStuffByEmail(personEmail: Email, i: Int): DoStuffPayload
}
```

…or do we only have a mutation using the global id?

**Comment by calebmer** [comment]
I also want to say thanks, keep opening issues questioning assumptions made in PostGraphQL 1. We’ve learned a lot and while I don’t want to make too many breaking changes in 2, I think it gives us a great chance to question our assumptions and make a better API :+1:

I’ll be opening an issue soon with some of the breaking changes I want to make and we can discuss them individually. There won’t be many and there will be backwards compatibility options for most of them :+1:

**Comment by ivosabev** [comment]
I think mutations should be only by global `id` and the `rowId` should not be given any primary key status, but be treated as a simple database column (like email).

The only update mutation will be:
```
mutation updateStuff($input: UpdateStuffPayload!) {
  updateStuff(input: $input) {
    id,
    rowId,
    email 
  }
}
{
  "input": {
     "id": "Xja1j=",
     "email": "new@email.com"
  }
}
```

I am not sure I understand your concern with the procedures?

**Comment by calebmer** [comment]
I’m going to close this as its in the PostGraphQL 2.0 beta 🎉 

Start playing with the pre-release, the final release should be out really soon. Tell me what you think! :+1:

```
npm install -g postgraphql@next
postgraphql
```
