### ISSUE TITLE
Oddities with connection pagination

### ISSUE THREAD

**Issue by ferdinandsalis** [calebmer/postgraphql#133]
With the following query
```
{
  postNodes(first: 3, descending: true, orderBy: CREATED_AT) {	
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
```
the response is as follows
```
{
  "data": {
    "postNodes": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": true,
        "startCursor": "W1sxM10sIjIwMTYtMDktMjZUMTk6MDg6MjcuMTI0WiJd",
        "endCursor": "W1syXSwiMjAxNi0wOS0yNlQxNTo1Njo1NC45NDVaIl0="
      }
    }
  }
}
```
however I was expecting `hasNextPage` to be true. Using `ROW_ID` in the orderBy yields the expected behaviour. Also there some more weirdness going on with argument `descending` and cursors. I am currently looking at the code to see if get any wiser. A second set of eyes is very much appreciated.

As way to better see this problems you should checkout the [infinite scrolling pagination](https://github.com/calebmer/postgraphql/blob/feat/relay-example/examples/forum-relay/src/components/PostIndexPage.js) that is now part of the relay example. Try to play around with the query variables `descending` and `orderBy`.

**Comment by calebmer** [comment]
Yeah, and you’d also expect `hasPreviousPage` to be false.

My guess would be that we are using the wrong operator here https://github.com/calebmer/postgraphql/blob/c69af04b19d8c3059743e04c8f4d31b995c6aebe/src/graphql/resolveConnection.js#L163 and here https://github.com/calebmer/postgraphql/blob/c69af04b19d8c3059743e04c8f4d31b995c6aebe/src/graphql/resolveConnection.js#L188

Maybe try going from:

```js
.add(getCursorCondition(endCursor, descending ? '<' : '>'))
```

…to just:

```js
.add(getCursorCondition(endCursor, '>'))
```

Maybe that will work? Unsure though. Try logging the SQL queries.

**Comment by calebmer** [comment]
Closing this as it should be fixed in PostGraphQL 2 :+1:
