### ISSUE TITLE
error: Expected type "ID", found 1.

### ISSUE THREAD

**Issue by RuniVN** [calebmer/postgraphql#14]
I got this error when I query users with id = 1
![screen shot 2016-04-28 at 5 52 22 pm](https://cloud.githubusercontent.com/assets/6028744/14883764/43cf219e-0d6a-11e6-8e8c-0ff69a59b929.png)

Any idea?

**Comment by calebmer** [comment]
`id` in this case is the opaque globally unique id, to get this value first refer to `usersNodes`. In the future we might add a `usersByRowId` field to support selection like this. Tell me if that's a feature you'd like 😊

**Comment by RuniVN** [comment]
Yay 👍  Thats what I am finding.

**Comment by calebmer** [comment]
Awesome, I'll close if you have any other questions, just ask.

You could also join the [Gitter](https://gitter.im/calebmer/postgraphql?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) to chat about your experiences with PostGraphQL 😊
