### ISSUE TITLE
`updateMyTable` seems successful when no rows edited

### ISSUE THREAD

**Issue by benjie** [calebmer/postgraphql#149]
(This is still for the released postgraphql, I've not had a chance to try 2.0 yet.)

I'm using Row Level Security, when I attempt to update a row that I can `SELECT` but cannot `UPDATE` using the inferred `updateMyTable` action, the action succeeds:

```json
{
  "data" : {
    "updateMyTable": {
      "clientMutationId": "0",
      "myTable": null
    }
  }
}
```

There were 0 rows affected but no error occurred so PostgraphQL returns success. To my mind the `updateMyTable` action takes a `rowId!` and thus should always result in exactly 1 row changed on success - so if 0 rows were affected an error should be raised. Do you agree? 

The reason for this is I'd like a failed update (where 0 rows were affected because it was blocked by RLS) to result in an `onFailure` event in Relay.

**Comment by calebmer** [comment]
This is fixed in 2.0, is there a reason you can’t upgrade? If so I’d like to fix that :blush:

**Comment by benjie** [comment]
Merely lack of time; the changes you've made sound excellent - particularly the __id stuff.

**Comment by calebmer** [comment]
I’ll close this then. Let me know if this is important for you to see in PostGraphQL 1 :+1:
