### ISSUE TITLE
Unable to use v2 as a library 

### ISSUE THREAD

**Issue by tim-field** [calebmer/postgraphql#158]
I've been using the following with v1

```
app.use('/graphql', postgraphql(DB_STRING, DB_SCHEMA, {
  anonymousRole: 'anon_role',
  development: (!process.env.NODE_ENV || process.env.NODE_ENV === 'development'),
  log: true,
  secret: SECRET
}))
```

Now from what I can tell by reading the source, this should correspond to the following in v2

```
app.use('/graphql', postgraphql(DB_STRING, [DB_SCHEMA], {
  pgDefaultRole: 'anon_role',
  classicIds: true,
  showErrorStart: true,
  graphiql: (!process.env.NODE_ENV || process.env.NODE_ENV === 'development'),
  jwtSecret: SECRET
}))
```

However, I can't get that ( or similar incarntations ) to work at all, express gives me a `Cannot GET /graphql` response. 

No errors are reported while starting the server.

Any ideas as to what I'm doing wrong here?

**Comment by calebmer** [comment]
Yep! So PostGraphQL now puts GraphiQL and the GraphQL endpoint on different routes 😊

This is so we can evolve GraphiQL separately, it also means PostGraphQL controls the routes (you can configure them with `graphqlRoute` and `graphiqlRoute`. So your example should change to:

`app.use(postgraphql(...))`, and you would go to the `/graphiql` to see the interface.

**Comment by calebmer** [comment]
The [library documentation](https://github.com/calebmer/postgraphql/blob/399a0b840b6e1aa0ee248fd30bc19d2532d36d56/docs/library.md) is updated with this information 👍

**Comment by tim-field** [comment]
Thanks @calebmer !
