### ISSUE TITLE
Option to disable/hide default mutations

### ISSUE THREAD

**Issue by ldesgoui** [calebmer/postgraphql#170]
Hello,

Currently, the grant/RLS system lets you block all mutations, but they still show in the schema through inspection.
An option to disable those CRUD mutations would be welcome in certain use-cases.

As discussed on gitter, it could simply be implemented with an option passed down to https://github.com/calebmer/postgraphql/blob/3e24703584bb4baaa460da589b072408020a8e1c/src/graphql/schema/getMutationGqlType.ts#L31-L38

Thanks

**Comment by calebmer** [comment]
Released in `v2.2.0`, hanks @grncdr :tada:
