### ISSUE TITLE
Does not connect to a specific database

### ISSUE THREAD

**Issue by lightsprint09** [calebmer/postgraphql#179]
When trying to connect to a specific DB like with `postgraphql postgres://localhost:5432/NameOfTheDB` it will connect to the default DB which is named as my username. This issue was introduced when I updated to 2.0.

I am using am Mac with MacOS 10.12 and Postgres 9.6

**Comment by calebmer** [comment]
Try:

```
postgraphql -c postgres://localhost:5432/NameOfTheDB
```

Note the `-c` or `--connection` 😊

**Comment by lightsprint09** [comment]
Thanks for the quick response. 

Works perfect.
