### ISSUE TITLE
Views (and every other table) requiring a primary key

### ISSUE THREAD

**Issue by Velmont** [calebmer/postgraphql#18]
It seems it is designed this way, but maybe for anyone Googling the error, it'd be good to get it in writing:

>  Error: PostgreSQL schema 'memberships' contains table 'product_stock' which does not have any primary key. To generate a GraphQL schema all tables must have a primary key.

Or is there a way around it?  You seem to generate your own ID's anyway, so maybe it could be done for the items where there's no primary key set?

**Comment by calebmer** [comment]
Version `1.1.0` removes this requirement

**Comment by calebmer** [comment]
Tell me if continue experiencing troubled in 1.1.0 😊

**Comment by Velmont** [comment]
I thought this was from the git repo, but when I think about it, I actually used the example, and the example used npm to download postgraphql, so indeed. :)

It'd be cool if the example could require/install the git repo version it itself is residing inside.  I'm not very familiar with Node though, so that might be strange and not good.  In Python projects, it's quite usual for the example to use the code it's downloaded with then.

**Comment by calebmer** [comment]
Thanks so much for the catch! I want the example to be installed independently of the repo, and I want the example to always work even if master has breaking changes.

As a compromise I set the version dependency to `latest` 😊
