### ISSUE TITLE
v2 regression: loss of conditions on reverse relations

### ISSUE THREAD

**Issue by benjie** [calebmer/postgraphql#187]
In v1 you could do a query like:

``` graphql
fragment on Viewer {
  currentUser {
    teamMembershipNodesByUserId(first: 20, accepted: true) {
      edges {
        node {
          ${Team.getFragment('teamMembership')}
        }
      }
    }
    teamMembershipNodesByUserId(first: 20, accepted: false) {
      edges {
        node {
          ${Invite.getFragment('teamMembership')}
        }
      }
    }
  }
}
```

In v2, this would be more like:

``` graphql
fragment on Query {
  currentUser {
    teamMembershipsByUserId(first: 20, conditions: {accepted: true}) {
      edges {
        node {
          ${Team.getFragment('teamMembership')}
        }
      }
    }
    teamMembershipsByUserId(first: 20, conditions: {accepted: false}) {
      edges {
        node {
          ${Invite.getFragment('teamMembership')}
        }
      }
    }
  }
}
```

But alas conditions are no longer supported on reverse relations.

I'd be happy to submit a PR for this, but I need some pointers to help me get started.

**Comment by calebmer** [comment]
Thanks for offering to contribute! The current code for handling conditions is in [`createCollectionQueryFieldEntries.ts`](https://github.com/calebmer/postgraphql/blob/8b365f2caa4e8f5019d846628716fc244056d786/src/graphql/schema/collection/createCollectionQueryFieldEntries.ts#L27-L66). This logic (including the `getPaginatorInput` function which should probably be renamed) should be moved to a `getConditionGqlType` function which is memoized and takes a type as the argument (for now just an `ObjectType` but I’d like to generalize to just a `Type` in the future).

You’ll then use the `getConditionGqlType` function with the relation connections in [`getCollectionGqlType.ts`](https://github.com/calebmer/postgraphql/blob/8b365f2caa4e8f5019d846628716fc244056d786/src/graphql/schema/collection/getCollectionGqlType.ts#L96-L104) similar to its integration in [`createQueryFieldEntries.ts`](https://github.com/calebmer/postgraphql/blob/8b365f2caa4e8f5019d846628716fc244056d786/src/graphql/schema/collection/createCollectionQueryFieldEntries.ts#L68-L80).

Hope that helps, let me know if you have more questions :+1:
