### ISSUE TITLE
Looking up node by __id returns different node?!

### ISSUE THREAD

**Issue by benjie** [calebmer/postgraphql#189]
I created a minimal test case to reproduce the issue on my schema:

```graphql
query {
  node(__id: "WyJ0ZWFtcyIsMTBd"){
    __typename
    __id
  }
  teamById(id: 10) {
    __id
    __typename
  }
}
```

(Note base64 decode of `WyJ0ZWFtcyIsMTBd` is `["teams",10]`)

This returns

```json
{
  "data": {
    "node": {
      "__typename": "User",
      "__id": "WyJ1c2VycyIsMTBd"
    },
    "teamById": {
      "__id": "WyJ0ZWFtcyIsMTBd",
      "__typename": "Team"
    }
  }
}
```

(base64 `WyJ1c2VycyIsMTBd` = `["users",10]`)

Which makes no sense - how has a `Team` turned into a `User`? They both have the same row id: 10; so could this be the reason somehow?

**Comment by benjie** [comment]
I've reproduced this same issue with PostGraphQL 2.0.0 and 2.1.1 and 2.2.0

**Comment by calebmer** [comment]
Looking into this :+1:

**Comment by calebmer** [comment]
Found the issue, to understand what was happening and to see a fix, check out https://github.com/calebmer/postgraphql/pull/192
