### ISSUE TITLE
Got an error when invoked postgraphql from command line

### ISSUE THREAD

**Issue by AlokJoshi** [calebmer/postgraphql#195]
Can you please help. I am new to graphql and maybe I am doing something wrong.

I installed postgraphql and then invoked it. I get the following error. I am on windows 7.

C:\Windows\system32>postgraphql
C:\Program Files\nodejs\node_modules\postgraphql\build\postgraphql\cli.js:46
const { demo: isDemo = false, connection: pgConnectionString, watch: watchPg, ho
st: hostname = 'localhost', port = 5000, maxPoolSize, defaultRole: pgDefaultRole
, graphql: graphqlRoute = '/graphql', graphiql: graphiqlRoute = '/graphiql', dis
ableGraphiql = false, secret: jwtSecret, token: jwtPgTypeIdentifier, cors: enabl
eCors = false, classicIds = false, dynamicJson = false, disableDefaultMutations
= false, showErrorStack, } = program;
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3

**Comment by hardchor** [comment]
What node version are you on?

**Comment by AlokJoshi** [comment]
I am on v5.11.0Alok

**Comment by calebmer** [comment]
Yep, this error is caused by your Node.js version. Try updating to Node.js v6+ 👍 

If you have a need for a version that supports a version lower than 6 then let’s reopen to discuss options.

**Comment by AlokJoshi** [comment]
Thank you. 


Sent from my T-Mobile 4G LTE Device

-------- Original message --------
