### ISSUE TITLE
No exception/warning if port in use

### ISSUE THREAD

**Issue by cmpis** [calebmer/postgraphql#2]
Just says it's listening, but in my case something was already listening on that port and it didn't say anything.

**Comment by calebmer** [comment]
I couldn't reproduce this 😐

I've started a [Gitter room](https://gitter.im/calebmer/postgraphql) if you wanted to talk about your experiences with PostGraphQL and we could use it to debug this.

**Comment by calebmer** [comment]
Closing this as I can't reproduce.
