### ISSUE TITLE
Auth RegisterUserPayload

### ISSUE THREAD

**Issue by valorize** [calebmer/postgraphql#200]
I went through the docs for authentication and authorization (https://github.com/calebmer/postgraphql/blob/787bbe4ee842e0d931989df88acbdb3a88e1c380/examples/forum/tutorial.md#authentication-and-authorization) and realized that the register function does not return an edge needed by relay.

**Comment by ferdinandsalis** [comment]
Hi there, thanks for reporting this issue. See https://github.com/calebmer/postgraphql/issues/203 for more detail.
