### ISSUE TITLE
New GraphQL release

### ISSUE THREAD

**Issue by mytototo** [calebmer/postgraphql#202]
The October 2016 GraphQL specification has been released as we can see here: https://github.com/facebook/graphql/releases/tag/October2016.

Do you have a todo list to upgrade and fix breaking changes?

**Comment by calebmer** [comment]
Mostly we just need to wait until GraphQL JS `0.8.0` gets released with @langpavel’s [addition of null value handling](https://github.com/graphql/graphql-js/pull/544) :wink:

Once that lands Greenkeeper should tell us if tests are failing, but even if they are not I’d like to take a look at how null literals are handled.

Also see https://github.com/calebmer/postgraphql/issues/108
