### ISSUE TITLE
Forum example fails to note required extensions

### ISSUE THREAD

**Issue by capouch** [calebmer/postgraphql#216]
I had several issues getting the forum tutuorial running, which seem to come back to my not having built the pgcrypto extension before trying to run the install SQL scripts.

Fresh install of Postgres 9.6.1.

I first got an error that the Python extension wasn't installed.  I installed it, and then got this error about pgcrypto:

`psql:schema.sql:122: ERROR:  could not open extension control file "/usr/local/pgsql/share/extension/pgcrypto.control": No such file or directory
`

I reverted to 9.6beta4, and there I only got the pgcrypo error, nothing about Python.

**Comment by calebmer** [comment]
Thanks for catching this! Didn’t know this could be a problem, `pgcrypto` has always worked fine out of the box with my [Postgres.app](http://postgresapp.com/) installation. How did you end up fixing this? It seems like `pgcrypto` should [come with your distribution](https://www.postgresql.org/docs/9.6/static/contrib.html).

**Comment by capouch** [comment]
There is precious little documentation about how to actually build Postgres extensions; some of them build via options in the configure script; others have to be installed "manually."  Pgcrypto appears to be one of the latter.  Googling didn't help me find an easier way. 

I use Slackware, which eschews the "let someone else decide for me" mindset; you have to learn to row your own boat.  This means a lot of package-manager-based automagic cannot be counted upon.  It also means you learn what's going on under the hood.

In this case, it was (as root) `cd <path-to-Postgres-sources)/contrib/extensions; make; make install`

I don't know where the Python extensions complaint came from when I ran the schema.sql script on a fresh 9.6.1 install.  If I get a chance I will do another clean install and see if I can reproduce that part of it.
