### ISSUE TITLE
Question about forum example

### ISSUE THREAD

**Issue by capouch** [calebmer/postgraphql#218]
I hope someone can explain the discrepancy in the means showing for starting postgraphl in the README for the forum tutorial, versus the much longer invocation string in the tutorial.

Both, from my testing, behave identically.

Are all those parameters in the tutorial "baked in" to the postgraphql executable?

Also, is there no way on the command line to specify an alternate database?  I am playing around and the original plan was different databases with the same schema in them, configured/populated differently as a means of learning.  That can be done via ENV variable, but there doesn't seem to be a way to do it from the command line?

**Comment by capouch** [comment]
Closed the wrong one!

**Comment by calebmer** [comment]
You can switch databases using the `--connection` (or `-c`) option which is touched upon briefly in the [Installing PostGraphQL](https://github.com/calebmer/postgraphql/blob/master/examples/forum/TUTORIAL.md#installing-postgraphql) section 😊

As for the argument discrepancies it really boils down to do you want auth or not and how do you want to configure it? The easiest way to get up and running is to ignore the auth options and just run `postgraphql` (which connects to the default database and schema). If you want to layer in auth you will need to add some extra options like a JWT secret and a default role.

**Comment by capouch** [comment]
Thanks.
