### ISSUE TITLE
Error: function pg_catalog.pg_relation_is_updatable(oid, boolean) does not exist

### ISSUE THREAD

**Issue by n1kt0** [calebmer/postgraphql#230]
Hello,
I've encountered this error: "function pg_catalog.pg_relation_is_updatable(oid, boolean) does not exist" when executing postgraphql.
My postgresql version is 9.2.15 if it helps.

Thanks in advance!

**Comment by benjie** [comment]
I'm not sure what the minimum supported version of postgresql is, but I can tell you that the tests run against PG 9.4 and PG 9.5; if you're able to upgrade to 9.4 or above you may have an easier time.

**Comment by n1kt0** [comment]
Thx, runs fine on pg 9.5!

**Comment by mjpuser** [comment]
Looks like it was added late 9.3 or 9.4
https://github.com/postgres/postgres/commit/dc3eb5638349e74a6628130a5101ce866455f4a3#diff-ea85df583e017327df4fa6cd74ceaafaR538
