### ISSUE TITLE
Using Express, is a post hook for a mutation possible?

### ISSUE THREAD

**Issue by shanestillwell** [calebmer/postgraphql#231]
I'm using the Express setup of PostGraphQL and I'm wondering if there is a way to run something on the node.js server after a user has been created. E.g. I want to send an email.

```
registerPerson()  ==> insert person in pg ==> queue email ==> respond to client.
```

**Comment by benjie** [comment]
There's currently no way to do this with express as you've requested, but you can do it with triggers within postgresql. Something like:

```sql
CREATE FUNCTION queue_row_task() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO job_queue (name, details)
    VALUES(TG_ARGV[0], json_build_object('id', NEW.id));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER send_welcome_email
  AFTER INSERT ON person
  FOR EACH ROW
  EXECUTE PROCEDURE queue_row_task('person__send_welcome_email');
```

(This was written off the top of my head, so you'll need to do some sanity checks!)

**Comment by calebmer** [comment]
You can also use [`pg-pubsub`](https://www.npmjs.com/package/pg-pubsub) with Postgres [`LISTEN`](https://www.postgresql.org/docs/9.6/static/sql-listen.html)/[`NOTIFY`](https://www.postgresql.org/docs/9.6/static/sql-notify.html) commands to accomplish a similar thing. There’s a great example in the [PostgREST docs](http://postgrest.com/examples/users/#password-reset) :+1:

**Comment by shanestillwell** [comment]
@calebmer @benjie thanks, looks like `pg_notify` is a viable solution for now.
