### ISSUE TITLE
Unhandled 'error' event when password authentication fails

### ISSUE THREAD

**Issue by kthornsbury** [calebmer/postgraphql#240]
When I try to connect to my postgresql instance from the command line, I get the following error message, even though I can connect directly using psql. I've tried using the -c option when running postgraphql, but that doesn't seem to work either. Any help would be appreciated!

PostGraphQL server listening on port 5000 🚀

  ‣ Connected to Postgres instance postgres://localhost:5432
  ‣ Introspected Postgres schema(s) public
  ‣ GraphQL endpoint served at http://localhost:5000/graphql
  ‣ GraphiQL endpoint served at http://localhost:5000/graphiql

* * *

events.js:160
      throw er; // Unhandled 'error' event
      ^

error: password authentication failed for user "root"
    at Connection.parseE (/usr/local/lib/node_modules/postgraphql/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/usr/local/lib/node_modules/postgraphql/node_modules/pg/lib/connection.js:381:17)
    at Socket.<anonymous> (/usr/local/lib/node_modules/postgraphql/node_modules/pg/lib/connection.js:117:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

**Comment by calebmer** [comment]
What are your environment variables that start with `PG*`?

**Comment by kthornsbury** [comment]
There aren't any PG* environment variables set. Are there any that should be?

**Comment by benjie** [comment]
It's possible that `psql` locally is using the peer authentication mode of postgres, whereas postgraphql is trying to use a network connection. See: https://www.postgresql.org/docs/9.5/static/auth-methods.html

Try using the same address for psql; for example:

```
psql "postgres://localhost:5432"
postgraphql -c  "postgres://localhost:5432"
```

You might also try explicit authentication (replace pg_user, pg_password and db_name with valid details):

```
psql "postgres://pg_user:pg_password@localhost:5432/db_name"
postgraphql -c  "postgres://pg_user:pg_password@localhost:5432/db_name"
```

**Comment by kthornsbury** [comment]
Thanks @benjie, I tried again with the explicit authentication, and that seemed to work.
