### ISSUE TITLE
smallint and boolean not cast to correct type

### ISSUE THREAD

**Issue by valorize** [calebmer/postgraphql#246]
@calebmer and @benjie I dived into the, boolean is unkown type in function call, problem. I found out that node-postgres is converting all "simple" values to a string so 1 results in "1" and false results in "false". It is done in `pg/lib/utils.js -> prepareValue -> return val.toString()`. I guess that's why @calebmer added
```
  if (
    type === integerType ||
    type === floatType
  )
    return sql.query`(${sql.value(value)} + 0)`
```
into `postgraphql/src/postgres/inventory/transformValueIntoPgValue.ts -> transformValueIntoPgValue`

The problem is that + 0 casts the value into an integer but I'am using a smallint and boolean in my function.

What do you think should we ask node-postgres why the convert every value to a string or should we add something like:
```
if(type === booleanType) {
		return sql.query`cast(${sql.value(value)} as boolean)`
}
```

**Comment by valorize** [comment]
I guess the problem with smallint is negligable. As you simply accept integer and convert it to smallint within your function

**Comment by benjie** [comment]
@valorize Could you file steps to reproduce or link the issue to which you refer, please? I haven't had any issues with booleans in my own project (I don't use smallints). A minimal test-case schema dump and query or mutation that can be ran through graphiql would be grand 👍

**Comment by valorize** [comment]
I would like to extend the tests with a test-case but I am a bit overwhelmed by the amount. Do you know if there is a test which creates a function and then tries to query results via this function?

**Comment by benjie** [comment]
Alas, I'm not at that level yet. But a small standalone schema (dump.sql) and a GraphQL mutation query to run against it might be a good way to start. Then we can just 

```
createdb issue246
psql issue246 < dump.sql
postgraphql -c postgres://localhost/issue246
open http://localhost/graphiql
```

and run the query to see the issue.

**Comment by calebmer** [comment]
@valorize the `c.types_mutation` is used in the [`procedure-mutation.graphql`](https://github.com/calebmer/postgraphql/blob/ce84c191e7273b9ded49f0007777ad369f58f823/src/postgraphql/__tests__/fixtures/queries/procedure-mutation.graphql#L11) integration test. I understand how it may be a little hard to find :wink:

Feel free to reproduce the error with that function, or add another function in any one of the schemas to reproduce. If we could get a SQL dump reproducing the issue that would be awesome too :blush:

**Comment by valorize** [comment]
It's really odd. I can't reproduce the boolean error anymore. But instead I sometimes get:

```
"errors": [
    {
      "message": "invalid input syntax for integer: \"\"",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "upsertAnswerVoteByQuestionAndAnswer"
      ]
    }
```

I think it is a kind of race condition because when I execute the exact same query again it only says permission denied to relation xyz (have not given update rights forum_example_anonymous in graphiql). Anyway I will close this ticket until the boolean error reappears. Thanks for your support so far. Protest when I shall investigate more but I guess it's somewhere deep down.
