### ISSUE TITLE
regex to convert table and field names

### ISSUE THREAD

**Issue by barbalex** [calebmer/postgraphql#250]
I am using https://github.com/kadirahq/lokka to fetch data from the graphql endpoint.

(Yep, I am using postgraphql without relay. Basically I am using the graphql server as an easy way to get an excellent api server out of the box. And the option to use relay later.)

This means I have to convert table names to postgraphql names (sorry for not using the correct expressions here - I am a graphql newbie) as in my application I fetch data dynamically depending on table names. For instance:

table `adb_eigenschaften` > `AdbEigenschaften`

There may be more to this than capitalizing and replacing underscores. So I would like to use the exact same regex as done in postgraphql.

I did try to find this in the source code but did not succeed.

Could you point me to the code please?

The same applies to field names. Maybe the naming convention is same as for table names?

**Comment by benjie** [comment]
I think what you're looking for is [formatName.ts](https://github.com/calebmer/postgraphql/blob/1da6f51837b9cce897e12d728142235d69885700/src/graphql/utils/formatName.ts) which uses the `camelCase` method from the [`change-case` npm module](https://www.npmjs.com/package/change-case); but I'm not certain. Does that help?

**Comment by barbalex** [comment]
yep, thanks a lot!
