### ISSUE TITLE
Throwing SyntaxError: Unexpected token { on postgraphql execution

### ISSUE THREAD

**Issue by onlyjazz** [calebmer/postgraphql#251]
npm install -g postgraphql
pg running on 5432 
postgraphql --help (fwiw - any command) throws syntax error because of an empty string in showErrorStack 
```

/usr/local/lib/node_modules/postgraphql/build/postgraphql/cli.js:46
const { demo: isDemo = false, connection: pgConnectionString, watch: watchPg, host: hostname = 'localhost', port = 5000, maxPoolSize, defaultRole: pgDefaultRole, graphql: graphqlRoute = '/graphql', graphiql: graphiqlRoute = '/graphiql', disableGraphiql = false, secret: jwtSecret, token: jwtPgTypeIdentifier, cors: enableCors = false, classicIds = false, dynamicJson = false, disableDefaultMutations = false, showErrorStack, } = program;
```

**Comment by onlyjazz** [comment]
actually the problem is that const is not a well-formed JSON object - since these are not key-value pairs

`cors: enableCors = false, classicIds = false, dynamicJson = false, disableDefaultMutations = false `

**Comment by calebmer** [comment]
What version of Node.js are you running? PostGraphQL runs on Node.js 6+. It looks to me like your version of Node.js may not support destructuring. If you need to support an older version of Node.js let me know :+1:

**Comment by onlyjazz** [comment]
was running node 5.9.x - upgraded to node 6.9.1 on os/x - works now.
