### ISSUE TITLE
Different results when running from command line and as a library

### ISSUE THREAD

**Issue by baloodevil** [calebmer/postgraphql#259]
Runs fine with no errors from the command line with...
`postgraphql -d postgres://postgres:mypassword@127.0.0.1:5432/mydatabase`

But shows different behavior when run as a library with...
```js
"use strict";
var express = require('express');
var postgraphql = require('postgraphql');
var app = express();
var postgraphql = require('postgraphql').default;
app.use(postgraphql('postgres://postgres:mypassword@127.0.0.1:5432/mydatabase'));
app.listen(3000);
```
Then running with `node app.js`
The behavioral difference is that when it is introspecting, it throws an error if there is a table ending with `_condition` and another table with the same name, less 'condition'.  So if there are tables `foo` and `foo_condition`, postgraphql (graphql actually) when used as a library will throw the error...
```
Error: Schema must contain unique named types but contains multiple types named "FooCondition".
    at invariant (C:\Users\me\myapp\node_modules\graphql\jsutils\invariant.js:19:11)
    at typeMapReducer (C:\Users\me\myapp\node_modules\graphql\type\schema.js:190:29)
    at typeMapReducer (C:\Users\me\myapp\node_modules\graphql\type\schema.js:187:12)
    at C:\Users\me\myapp\node_modules\graphql\type\schema.js:217:22
    at Array.forEach (native)
    at C:\Users\me\myapp\node_modules\graphql\type\schema.js:208:29
    at typeMapReducer (C:\Users\me\myapp\node_modules\graphql\type\schema.js:219:7)
    at typeMapReducer (C:\Users\me\myapp\node_modules\graphql\type\schema.js:187:12)
    at C:\Users\me\myapp\node_modules\graphql\type\schema.js:217:22
    at Array.forEach (native)
```

**Comment by calebmer** [comment]
I'd expect that error to happen, but I'm confused why it works in the CLI. Maybe your CLI version is pre 2.0 and your installed version is 2.0+?

Is renaming the `foo_condition` table an option?

**Comment by baloodevil** [comment]
Yep.  That was right, the CLI was using a previous version.  Renaming the table is an option.  Would be better without renaming, because it breaks a larger naming convention, but still doable.  Thanks Caleb.
