### ISSUE TITLE
Getting a weird error: Cannot have two definitions for property 'stForce2d'.

### ISSUE THREAD

**Issue by ajalger** [calebmer/postgraphql#260]
I am getting a weird error after starting everything up using express. I am trying to connect to an external database.

`Error: Naming conflict when building object. Cannot have two definitions for property 'stForce2d'.`

Any clue on how to get out of this problem?

**Comment by calebmer** [comment]
What does your schema look like? Also, what is the full stack trace of the error? Do you expect a column with this name to be in the API?

I'm thinking either you have two columns which convert to that name, or you have a procedure that conflicts with a column name?

**Comment by ajalger** [comment]
I was just trying to connect to an external database. So, I didn't have the schema defined. I was just importing postgraphql and making a DB connection. The I was going to see what the output was. That's where I got the error.

**Comment by calebmer** [comment]
That's helpful. Do you mind running [the introspection query](https://github.com/calebmer/postgraphql/blob/5b8b04349ad5902854b3e4ee57d92164245db355/resources/introspection-query.sql) and providing the result? Just change [this line](https://github.com/calebmer/postgraphql/blob/5b8b04349ad5902854b3e4ee57d92164245db355/resources/introspection-query.sql#L18) to `= 'my_schema_name'`. If you don't feel comfortable sharing the result publicly you can DM me on [Gitter](https://gitter.im/calebmer) or send me an email (public on GitHub).

**Comment by benjie** [comment]
`st_force_2d` and `st_force2d` are two function in PostGIS that would both translate to the same PostGraphQL identifier; try using a schema other than `public` via the [`schemaName` option](https://github.com/calebmer/postgraphql/blob/master/docs/library.md) so that you only pull in functions and tables you deliberately want to expose rather than also including all the utility functions.

**Comment by ajalger** [comment]
Yep @benjie that worked. Just changed the schemaName.

**Comment by benjie** [comment]
Excellent, glad to hear you're up and running!
