### ISSUE TITLE
orderBy computed column possible?

### ISSUE THREAD

**Issue by valorize** [calebmer/postgraphql#262]
I have a computed column like:
```
CREATE FUNCTION answer_vote(answer answer) RETURNS integer
    LANGUAGE sql STABLE
    AS $$
  select sum(a.value)::integer from answer_vote a
  where a.question = answer.question AND a.answer = answer.id
$$;
```

Is it possible to order on a computed column?

**Comment by calebmer** [comment]
Yep! Using a procedure:

```sql
create function answers_ordered_by_vote() returns setof answer as $$
  select *
  from answer
  order by answer_vote(answer)
$$ language sql stable;
```

My syntax may be wrong, eyeballing it, but that’s the gist :wink:

**Comment by valorize** [comment]
I hoped for a more automatic solution. But will take that for now.

**Comment by bpb27** [comment]
@calebmer @valorize has there been any update on this? i have a computed column that returns a `SETOF` so it's a bit more complicated, and wondering if there's any automated solution since this last arose?

**Comment by garcianavalon** [comment]
This is the second time in a month that I google this question and end up here, so for future me and others looking for an answer:

Ordering by scalar computed columns is supported by smart comment `@sortable`. You can check the [PR here](https://github.com/graphile/graphile-engine/pull/378) and the [release notes here](https://github.com/graphile/postgraphile/releases/tag/v4.3.1)

Sadly this is not documented yet, I'm opening an [PR here](https://github.com/graphile/graphile.github.io/pull/154) to the docs
