### ISSUE TITLE
windows connection error?

### ISSUE THREAD

**Issue by paOol** [calebmer/postgraphql#273]
if I type 
```
postgraphql -c postgres://user:password@localhost:5432/postgres
```
then i get a graphiql server at localhost:5000/graphiql.

however, if I try to run it from within koa 
```
app.use(async(ctx, next) => {

  postgraphql(postgraphql({
    pgConfig: 'postgres://postgres:pw@localhost:5432/postgres',
    schemaName: 'public',
    options: {
      graphiql: true,
      enableCors: true
    }
  }));

  winston.log('debug', 'PostGraphQL connection established');
  await next();
});

```

i get 
```
debug: PostGraphQL connection established
  error: role "paool-Desktop" does not exist

```

why is the role my windows pc name? is there any error in my postgrahpql object?

**Comment by lcjnil** [comment]
Your arguments passed to postgraphql is wrong( see https://github.com/calebmer/postgraphql/blob/master/docs/library.md).

the `pgConfig`, `schemaName` should be passed as arguments[0] and arguments[1].

:unamused: I was like you before, maybe @calebmer  should consider change the way the arguments passed

**Comment by paOol** [comment]
@lcjnil are you on windows?
I am getting the same error when trying
```
 postgraphql( postgraphql(postgres://postgres:pw@localhost:5432/postgres') );
```

**Comment by paOol** [comment]
should note it works with `http` using the same exact arguments.

```
http.createServer(postgraphql(
  'postgres://postgres:pw@localhost:5432/postgres',
  'public',
  {graphiql: true, enableCors: true}
  )).listen(4000)

```

**Comment by benjie** [comment]
@paOol Why are you passing postgraphql to itself via `postgraphql(postgraphql(...))`? It looks like the first call is not seeing any expected options and thus is connecting to the default database.

Try instead:

```js
const app = new Koa();

app.use(postgraphql('postgres://postgres:pw@localhost:5432/postgres', 'public', {
  graphiql: true,
  enableCors: true
}))
```

**Comment by paOol** [comment]
got it working
```

app.use(
  postgraphql(
        
`postgres:${config.USER}:${config.PASSWORD}@${config.HOST}:${config.PORT}/${config.DBNAME}`, //concat to shorten later
    'public', //schema
    { graphiql: true } //options

  )
);
```
