### ISSUE TITLE
postgres user not recognised as superuser i.e --watch not available

### ISSUE THREAD

**Issue by visiperf** [calebmer/postgraphql#276]
Hello guys, 

When launching postgraphql with a postgres superuser I get this warning followed by the abortion of the process. I am connecting using : 

`postgraphql -c postgres://user:password@localhost:5432/db --watch`

> Failed to setup watch fixtures in Postgres database ️️⚠️
> This is likely because your Postgres user is not a superuser. If the
> fixtures already exist, the watch functionality may still work.
> error: current transaction is aborted, commands ignored until end of transaction block
>     at Connection.parseE (/usr/local/lib/node_modules/postgraphql/node_modules/pg/lib/connection.js:554:11)
>     at Connection.parseMessage (/usr/local/lib/node_modules/postgraphql/node_modules/pg/lib/connection.js:381:17)
>     at Socket.<anonymous> (/usr/local/lib/node_modules/postgraphql/node_modules/pg/lib/connection.js:117:22)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at readableAddChunk (_stream_readable.js:176:18)
>     at Socket.Readable.push (_stream_readable.js:134:10)
>     at TCP.onread (net.js:551:20)

Thanks in advanced for your help.

**Comment by benjie** [comment]
@visiperf What version of postgres are you using? I think it needs to be at least 9.4; I'm running 9.6.

**Comment by visiperf** [comment]
@benjie I am using PostgreSQL 9.3.5. I will try to upgrade to 9.6 and let you know. Thanks for the tip :)

**Comment by benjie** [comment]
@visiperf I'm going to close this because I think it's solved - if not please feel free to re-open it 👍
