### ISSUE TITLE
Creating a schema file on watch reload

### ISSUE THREAD

**Issue by artronics** [calebmer/postgraphql#282]
Hello everyone,
given `watchPg` is enabled, is there any way I can call a callback function on schema changes?

I need this to recreate a schema file for [babel-plugin-graphql](https://github.com/ooflorent/babel-plugin-graphql) on each call.

Currently I'm using [fetch-graphql-schema](https://www.npmjs.com/package/fetch-graphql-schema) to fetch schema.json and schema.graphql, however any time I change my schema I need to go through the process manually to update these files. 

It would be great if `postgraphql` could generate these files automatically. It is very useful during development when the schema is changing rapidly.

**Comment by calebmer** [comment]
Yep, @ferdinandsalis has talked about this. I think this feature would be best baked directly into the library, I’m totally willing to merge PRs adding this feature 😊

(I’m also going to rename this issue to “creating a schema file on watch reload” if that’s ok with you)

**Comment by artronics** [comment]
👍 Great Thank you :)
