### ISSUE TITLE
Improving Updates?

### ISSUE THREAD

**Issue by pyros2097** [calebmer/postgraphql#288]
Just read this article.
http://blog.2ndquadrant.com/postgresql-anti-patterns-read-modify-write-cycles/
And was thinking maybe updating numbers should be done like this set value = value + (new - old) and and would prevent those weird issues.

**Comment by benjie** [comment]
@pyros2097 That's not a good pattern to have as default in a project like postgraphql - it can go wrong in hard to reason about ways. However, if this pattern is suitable for your app it's very easy to do in postgraphql - you just create an `increment` mutation, e.g.

```
create function increment_foo(delta integer) returns void as $$
  update table_name set foo = foo + delta;
$$ language sql;
```

Then you can just perform the `incrementFoo(delta: 2)` mutation.

**Comment by pyros2097** [comment]
Yeah seems good. Totally forgot about the mutation function. Thanks.
