### ISSUE TITLE
Postgres BigInt overflowing GraphQL Int

### ISSUE THREAD

**Issue by colophonemes** [calebmer/postgraphql#302]
My db key generation function uses a `bigint` field type and generates Integers that are in the range `2^40` to `2^52` (i.e. below the Javascript `Number.MAX_SAFE_INTEGER` limit of `(2^53)-1`). However numbers of this size throw an error:

```json
{
  "data": {
    "userByEmail": null
  },
  "errors": [
    {
      "message": "Int cannot represent non 32-bit signed integer value: 467131188225",
      "locations": [
        {
          "line": 17,
          "column": 5
        }
      ],
      "path": [
        "userByEmail",
        "id"
      ]
    }
  ]
}
```

(Context for key generation: https://gist.github.com/colophonemes/42b4167632a96a78a985fd14b4b0c013)

Is there an easy way to work around this in PostGraphQL, other than casting the numbers to text (which I think has performance implications for indexing) or using something like UUIDs? It looks like the GraphQL `Int` spec caps out at `(2^32)-1` but might it be possible to automatically cast BigInts to strings (at the PostgraphQL layer, rather than in the storage) or create a larger scalar type (cf the discussion [here](https://github.com/mickhansen/graphql-sequelize/issues/144)?

**Comment by calebmer** [comment]
Would you be comfortable if we added our own custom type which was an integer for valid JavaScript integers, but then switch to strings for larger values?

**Comment by colophonemes** [comment]
Yeah, that seems totally fine for my use case, although I guess it might lead to strange behaviour if people aren't expecting typecasting to be contingent on integer size.

**Comment by calebmer** [comment]
There’s a PR open to fix this https://github.com/calebmer/postgraphql/pull/328. It’s a breaking change so I wanted to wait for the `3.x` release which should be happening soon now 😊

**Comment by colophonemes** [comment]
Awesome, love your work!
