### ISSUE TITLE
forum example: how to use search operators

### ISSUE THREAD

**Issue by mrbarletta** [calebmer/postgraphql#31]
thanks for the kool project! looks primising.

I was wondering how to use the search operators (e.g. like givenName: '%partOfName%')

Do we have to extend the exposed methods? is that even possible? 

thanks!

**Comment by calebmer** [comment]
I haven't thought of a good way to represent complex operators in the GraphQL type system. However, I am planning to finish support for calling PostgreSQL procedures soon. You can actually see the branch [here](https://github.com/calebmer/postgraphql/tree/feat/procedures) where I currently have mutative procedures implemented.

Relevant parts from that branch include [this](https://github.com/calebmer/postgraphql/blob/feat/procedures/examples/forum/schema.sql#L117-L123) new example procedure and [this](https://github.com/calebmer/postgraphql/blob/feat/procedures/tests/integration/fixtures/procedure-mutation.graphql) passing test showing off procedures that perform mutations.

**Comment by gilesbradshaw** [comment]
have you any thoughts about how the existing graphql schema produced by postgraphql could be extended to add aditional parameters?

**Comment by calebmer** [comment]
Not too many yet. After the procedure stuff gets implemented and we have a good story for authentication, I want to work on the node API side to allow people to extend their schema however they want.

**Comment by calebmer** [comment]
@mrbarletta check out version `1.3.0-0` and #41 and tell me how that works for you 👍

**Comment by calebmer** [comment]
Procedure support is released in `1.3.0`. I wrote [this](https://github.com/calebmer/postgraphql/blob/master/docs/advanced-queries.md) new article with your issue in mind 😉

If it's inadequate in explaining the new feature, please tell me. Also you can follow #47 where simple free-form filtering using conditions will be possible.
