### ISSUE TITLE
Hiding objects from schema generation.

### ISSUE THREAD

**Issue by angelosarto** [calebmer/postgraphql#323]
I may have missed this, but is there a way to hide objects from appearing in the schema?

I tried revoking privelages on individual tables, but I imagine the schema generation is taking place through reading postgress schemas.

Any hints?

**Comment by benjie** [comment]
@angelosarto There's no blacklist functionality yet, but how I do it is moving things that I wish to be accessible into a specific schema for postgraphql.

**Comment by angelosarto** [comment]
This is actually a great answer and will do exactly what I need.

Plus, since you can specify multiple schemas to introspect it is possible to have this arrangement.

Server                                  |Parameters
-|-
graphql_external_unauth    |--schema unauth_api
graphql_external_auth        |--schema unauth_api auth_api
graphql_internal                  |--schema unauth_api auth_api private

So each server can show different apis but be the same underneath.

**Comment by calebmer** [comment]
@angelosarto that’s a pretty cool use case 😊
