### ISSUE TITLE
graphiQL broken?

### ISSUE THREAD

**Issue by martinheidegger** [calebmer/postgraphql#330]
The html output of `/graphiql` Does not output any JavaScript code and shows an empty page:

https://github.com/calebmer/postgraphql/blob/939a91ed20fc183bcd0fc8367a7b6af891e6a2de/src/postgraphql/graphiql/public/index.html

**Comment by calebmer** [comment]
That file is built with `create-react-app` which injects a script tag 😊

What environment are you currently working in? I don’t think that refactor has been published. You should be able to start a `create-react-app` server with `./scripts/dev` in development mode.

**Comment by martinheidegger** [comment]
As mentioned in #334 it seems like scripts/dev works at my computer now (don't have the logs of when it broke) so development works. Sorry for taking your time.
