### ISSUE TITLE
How to have custom authorization, authentication and logging

### ISSUE THREAD

**Issue by zusamann** [calebmer/postgraphql#335]
Hi, thanks for this great tool!

I was looking to use it as a microservice in my stack to provide a gql api. But it seems to be a bit opinionated in the way it works. Which is not a bad thing.

Just wanted to know how to get a hold of some of the abstractions or how to build them myself, in order to make postgraphql work consistently with the rest of my set of micro services.

For authorization and authentication, maybe I can build hooks that fire before a query is made. How about controlling other things like a logging or even a profiling/benchmarking middleware.

**Comment by benjie** [comment]
Regarding authentication, I mount postgraphql as an express middleware, and prefix it with a middleware which generates a JWT given the current session data:

```
    const populateJWT = (req, res, next) => {
      req.headers.authorization = 'bearer ' + getJWTToken(req, res);
      next();
    };
    expressApp.use('/graphql', populateJWT);
    expressApp.use('/graphiql', populateJWT);
    expressApp.use(postgraphql(pgPool, schemaName, options));
```

https://github.com/calebmer/postgraphql/blob/master/docs/pg-jwt-spec.md

**Comment by zusamann** [comment]
Yes, that would take care of authorization and authentication with hooks that fire before a request is made. Can conceptualize it like so:

```
// Initialize our service
app.use(postgraphql(...args));

// Get our initialized service so that we can bind hooks
const gqlService = app.service('/graphql');

const authHook = options => {
  return hook => {
    console.log('do something here....');
    return Promise.resolve(hook);
  };
};

// Set up our before hook
gqlService.before({
  all: [authHook()]
});
```

I guess the logging and profiling can both happen similarly with a before and an after hook.

But then any way to override the included default logging, or make it optional rather?

**Comment by zusamann** [comment]
Actually I did find an option that you can pass to stop the logging.

https://github.com/calebmer/postgraphql/blob/master/docs/library.md#postgraphqlpgconfig-schemaname--public-options
```
disableQueryLog: Turns off GraphQL query logging. By default PostGraphQL will log every GraphQL query it processes along with some other information. Set this to true to disable that feature.
```

So essentially, as I understand, postgraphql can be used like any other express middleware.
