### ISSUE TITLE
is it possible to limit or exclude tables for use in mutations

### ISSUE THREAD

**Issue by rhelenagh** [calebmer/postgraphql#341]
Hello, I have a question is it possible to limit or exclude tables for use in mutations. I would appreciate a small example. Congratulations on the project, very good !. :-)

**Comment by calebmer** [comment]
Yep! The mutations should be hidden if you did not grant insert, update, or delete privileges to the Postgres user you connected with 😊

So if you use a connection string of `postgres://postgraphql_user@localhost:5432`, and you:

```sql
grant select on post to postgraphql_user;
```

…but you do not grant insert, update, or delete privileges with:

```sql
grant insert, update, delete on post to postgraphql_user;
```

Then those mutations should be hidden in the schema.

For more information about the `GRANT` command, here is the documentation: https://www.postgresql.org/docs/9.6/static/sql-grant.html

**Comment by rhelenagh** [comment]
Geil, great thanks for your information!

**Comment by calebmer** [comment]
If you have any more questions, please feel free to leave a comment or reopen this issue 😊
