### ISSUE TITLE
Confusion about authentication in TUTORIAL.md

### ISSUE THREAD

**Issue by 5argon** [calebmer/postgraphql#359]
I have followed the entire tutorial to the point that I know `authenticate` will create the JWT to user, and PostgraphQL will use the JWT that is embedded in HTTP request’s Authorization header.

From what I understand `authenticate` would be available for query with GraphQL via reflection as well, so that is how client will get the JWT string (Do a GraphQL query with your ID and Password). Could someone guide me to put the JWT from `authenticate` into user's browser so it uses that on every future HTTP requests? (Of course it would need some kind of time out too)

From my guess I will need to do a GraphQL query via [the fetch API](https://developer.mozilla.org/en/docs/Web/API/Fetch_API) with the `method` set as POST so the password would not show up in the URL, to get the JWT and then put that into `document.cookie`. Next I will keep using that cookie with all further fetch API but with one of the `headers` set to Authorization : JWT string.

I haven't try this, but I am wondering if this is the recommended way or not. Thank you.

**Comment by benjie** [comment]
Here's what I use for an express stack, perhaps it's of use?

```js
    const getJWTToken = (req, res) => (
      jwt.encode({
        aud: 'postgraphql',
        role: postgraphqlRole,
        user_id: (req.user && req.user.id) || undefined,
      }, process.env.JWT_SECRET)
    );

    const populateJWT = (req, res, next) => {
      req.headers.authorization = 'bearer ' + getJWTToken(req, res);
      next();
    };

    expressApp.use('/graphql', populateJWT);
    expressApp.use('/graphiql', populateJWT);
    expressApp.use(postgraphql(pgPool, postgraphqlSchema, options));
```

(I use regular session management, and then convert that to a JWT token for PostGraphQL.)

**Comment by aabluedragon** [comment]
@5argon 

Here's a standalone example:
```
query(request) {
      let data = {};
      if (request.query) data['query'] = printGraphQL(request.query);
      if (request.variables) data['variables'] = JSON.stringify(request.variables || {});
      if (request.debugName) data['debugName'] = request.debugName;
      if (request.operationName) data['operationName'] = request.operationName;
      let headers = {Accept: 'application/json', 'content-type': 'application/json'};

      // get the JWT from local storage if it exists 
      let jwt = localStorage.getItem('jwt');
      if (jwt) {
        headers['Authorization'] = `Bearer ${jwt}}`;
      }
      return fetch(url, {headers, body: JSON.stringify(data), method: 'POST',}).then(result => result.json());
}
```

If you're using `apollo-data`'s client for your browser side code, look into the methods `networkInterface.use` and `applyMiddleware`, otherwise the above example should work out for you.

Notice we're using the http `fetch` API, some browsers may require [a polyfill](https://github.com/github/fetch).

**Comment by 5argon** [comment]
Thank you everyone. I have learned many things!
