### ISSUE TITLE
Expose defaultQuery and other options in graphiql?

### ISSUE THREAD

**Issue by pyros2097** [calebmer/postgraphql#360]
Whenever me or any developer opens graphiql I want to list all queries and mutations that are possible to him, so its easier to test the api immediately. I generally have a .md file that lists all the mutations to seed the database so this will be helpful in this case also which I will use  to populate the default query.

Or else since postgraphql already knows all the queries and mutations can it populate all of them with maybe empty values so that we could try it out without painful typing (something like swagger)?

**Comment by calebmer** [comment]
In the top right corner of any instance of GraphiQL is a documentation explorer 😊

For example see the SWAPI GraphiQL instance: http://graphql.org/swapi-graphql

From that you can explore the GraphQL API. Perhaps PostGraphQL should open the documentation explorer by default on large screens? I’d be happy to merge a PR that implements this.

I’m going to close, but let me know if I’m missing something in your question/feature request 😊
