### ISSUE TITLE
Is it still Relay-compliant that Node's id is "nodeId" instead of "id" ?

### ISSUE THREAD

**Issue by 5argon** [calebmer/postgraphql#363]
From http://facebook.github.io/relay/graphql/objectidentification.htm it indicates that the introspection should return 

```
{
  "__type": {
    "name": "Node",
    "kind": "INTERFACE",
    "fields": [
      {
        "name": "id",
        "type": {
          "kind": "NON_NULL",
          "ofType": {
            "name": "ID",
            "kind": "SCALAR"
          }
        }
      }
    ]
  }
}
```

But when I tested PostgraphQL it returns :

```
{
  "data": {
    "__type": {
      "name": "Node",
      "kind": "INTERFACE",
      "fields": [
        {
          "name": "nodeId",
          "type": {
            "kind": "NON_NULL",
            "ofType": {
              "name": "ID",
              "kind": "SCALAR"
            }
          }
        }
      ]
    }
  }
}
```

So I am wondering if Relay still functioning correctly despite this? (cache, optimistic update, etc.)

**Comment by benjie** [comment]
Look into `--classic-ids`; this change is to make it so the common `id` field for database tables doesn't conflict with the Relay one (which was `__id` until recently).

**Comment by calebmer** [comment]
Perhaps we should consider making `--classic-ids` the default again now? 🤔

But yeah, `--classic-ids` is required for Relay 1 support. I’ll close. Let me know if you have any more questions for us 😊

**Comment by srghma** [comment]
@benjie @calebmer I have a question about current state of art

I'm using relay modern 1.7, postgraphile generates schema with `nodeId: ID! (global id), id: Int (row id)`

I have an error during rendering `Invariant Violation: RelayResponseNormalizer: Expected id of elements of field `nodes` to be strings`

1. Do I need to use `--classic-ids` flag and change table id field from `id` to `rowId`?
2. OR Can I pass setting to relay to change default global id field from `id` (current) to `nodeId`?

**Comment by benjie** [comment]
Unsure; I don't use Relay and any time I've tested with it I've always used `--classic-ids`. @chadfurman can you shed some light as you're more familiar with Relay than I?
