### ISSUE TITLE
Emit the actual listen port during startup

### ISSUE THREAD

**Issue by cbandy** [calebmer/postgraphql#364]
When starting PostGraphQL as a child process, I'd like to communicate with it over any available TCP port. I can invoke it with `-p0` to choose such a port, but from outside the process, it's not easy to find which port was used.

```
→ postgraphql -p0

PostGraphQL server listening on port 0 🚀
```

I would love it if this line printed [`address().port`](https://nodejs.org/api/net.html#net_server_address) of `http.Server` instead.

**Comment by calebmer** [comment]
I’d love to merge a PR adding this feature 😊

It should be a simple one line change here: https://github.com/calebmer/postgraphql/blob/54879f694b3918d256fedf84071703ea4dd5ec10/src/postgraphql/cli.ts#L126
