### ISSUE TITLE
Relay transform error ``Maximum call stack size exceeded``

### ISSUE THREAD

**Issue by 5argon** [calebmer/postgraphql#373]
I have tried a simple PostgreSQL database with a table called `Employee`. In GraphiQL it seems fine, (I can do `query{ allEmployees { edges { node { ...` to get all Employees)  but when I tried integrating this with Relay I get this error. (probably on the transpiring step)

`Error: Relay transform error ``Maximum call stack size exceeded`` in file /Users/***/UserManager.js. Try updating your GraphQL schema if an argument/field/type was recently added.`

I have `Route` and container setup like this : 
```
const UserManager = Relay.createContainer(UserManagerNoRelay,{
  fragments: {
    allEmployees : () => Relay.QL`
    fragment on EmployeesConnection {
      edges {
        node {
          firstname
        }
      }
    }
    `
  }
});

export default UserManager;
```

```
class UserManagerRoute extends Relay.Route {}
UserManagerRoute.queries = {
  allEmployees : () => Relay.QL`
  query{
    allEmployees
  }
  `
}

export default UserManagerRoute;
```

Then the two would be combined together like this

```
class RelayWrapperPresentation extends Component {
  render() {
    return (
      <Relay.Renderer Container={UserManager} queryConfig={UserManagerRoute} environment={Relay.Store} />
    );
  }
}
```

From what I understand the fragment has to be `on EmployeesConnection` since I want it to expand on the query which has `allEmployees`. So I can access all Employee's data in the fragment.

The error sounds like an infinite loop that babel-relay-plugin tries to solve when looking through the introspected schema. So I am wondering if the problem came from schema generated from PostgraphQL or not.

Actually, I have one more table in other schema for password as a separation of concern (as I followed the step-by-step tutorial) but that should not be a problem since GraphQL could not access that schema and table. The only thing that links them to the schema with Employee are that the PK of Employee is a foreign key of the password table.

**Comment by valorize** [comment]
I've only worked with https://github.com/relay-tools/react-router-relay and the Relay.RootContainer. But could you try following: 
```
query{
  query {
    allEmployees(first:20)
  }
}
```

or
```
const UserManager = Relay.createContainer(UserManagerNoRelay, {
	fragments: {
		// The property name here reflects what is added to `this.props` above.
		// This template string will be parsed by babel-relay-plugin.
		allEmployees: () => Relay.QL`
			fragment on EmployeesConnection {
			  edges {
			    node {
			      firstname
			    }
			  }
			}`,
	},
})

export default UserManager;

class QuestionQueries extends Relay.Route {
	routeName = 'UserManagerRoute';
	queries = {
		allEmployees: (Component) => Relay.QL`query { allEmployees(first:20) { ${Component.getFragment('allEmployees')} } }`,
	};
}

export default UserManagerRoute;
```

**Comment by benjie** [comment]
You may need to clear out the babel cache - kill everything and then remove the `node_modules/.cache` folder and your `~/.babel.json` file and try again.

**Comment by 5argon** [comment]
@benjie Thank you, with this I am able to 100% reproduce the error, but haven't found the solution yet.

I have made a very simple `Human` table in a `test` schema. The `Human` table only contains a field `name`. The error appears when I set `name` as a primary key. (On my main program's data, the error disappears too when I removed the table's primary key and related foreign keys)

Is this means I cannot use any primary key in PostgreSQL? It's true that I might not need PK when I have a power of GraphQL, but it feels wrong.

Anyway, I have dumped an SQL with `pg_dump`. Here is the database that works :

```
--
-- PostgreSQL database dump
--

-- Dumped from database version 9.6.2
-- Dumped by pg_dump version 9.6.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: test; Type: SCHEMA; Schema: -; Owner: sargon
--

CREATE SCHEMA test;


ALTER SCHEMA test OWNER TO sargon;

SET search_path = test, pg_catalog;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: Human; Type: TABLE; Schema: test; Owner: sargon
--

CREATE TABLE "Human" (
    "Name" character(10) NOT NULL
);


ALTER TABLE "Human" OWNER TO sargon;

--
-- Name: COLUMN "Human"."Name"; Type: COMMENT; Schema: test; Owner: sargon
--

COMMENT ON COLUMN "Human"."Name" IS 'his name';


--
-- Data for Name: Human; Type: TABLE DATA; Schema: test; Owner: sargon
--

COPY "Human" ("Name") FROM stdin;
John      
Dave      
Tony      
\.


--
-- PostgreSQL database dump complete
--
```

Here is the one that does NOT works

```
--
-- PostgreSQL database dump
--

-- Dumped from database version 9.6.2
-- Dumped by pg_dump version 9.6.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: test; Type: SCHEMA; Schema: -; Owner: sargon
--

CREATE SCHEMA test;


ALTER SCHEMA test OWNER TO sargon;

SET search_path = test, pg_catalog;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: Human; Type: TABLE; Schema: test; Owner: sargon
--

CREATE TABLE "Human" (
    "Name" character(10) NOT NULL
);


ALTER TABLE "Human" OWNER TO sargon;

--
-- Name: COLUMN "Human"."Name"; Type: COMMENT; Schema: test; Owner: sargon
--

COMMENT ON COLUMN "Human"."Name" IS 'his name';


--
-- Data for Name: Human; Type: TABLE DATA; Schema: test; Owner: sargon
--

COPY "Human" ("Name") FROM stdin;
John      
Dave      
Tony      
\.


--
-- Name: Human Human_pkey; Type: CONSTRAINT; Schema: test; Owner: sargon
--

ALTER TABLE ONLY "Human"
    ADD CONSTRAINT "Human_pkey" PRIMARY KEY ("Name");


--
-- PostgreSQL database dump complete
--
```

And here is what I used as a GraphQL query string, also simplest possible : 

The route
```
const UserManagerRoute = { 
queries :{
  allEmployees : () => Relay.QL`
  query{
   allHumans
  }
  `
},
 params: {
    limit: '100000'
  },
 name: 'UserRoute'
}
```

The fragment
```
const userManagerRelay = Relay.createContainer(UserManager,{
  fragments: {
    allEmployees : () => Relay.QL`
    fragment on HumansConnection{
      edges {
        node 
        {
          name
        }
      }
    }
    `
  }
});
```

For now, I will go on without the primary key as a workaround.

**Comment by 5argon** [comment]
Hey! I managed to get it working with PKs + FKs! I just enabled `classicIds` option and it solves everything!

I saw you talk about this is a Relay 1 support so I assume the latest version of `react-relay` is already Relay 2, which is not the case. Anyway, thank you all for the supports!
