### ISSUE TITLE
Default value for first argument

### ISSUE THREAD

**Issue by danielbuechele** [calebmer/postgraphql#381]
Currently, if there is no `first` argument set, all items are queried on a connection. In my case this crashes the browser using GraphiQL. Is there a a way to set a default value, so you don't accidentally query **all** items of a connection?

**Comment by benjie** [comment]
No, but you could either replace it with an SQL function that does its own limits or you could implement validation on the incoming queries that will throw an error if no `first` or `last` argument is presented.

**Comment by danielbuechele** [comment]
For the latter solution I would need to traverse the AST of the GraphQL-request and check all fields, if they are connection and whether a `first`/`last` is set, right?
Would you think it makes sense to add this to PostGraphQL itself?

**Comment by benjie** [comment]
Have a look at the GraphQL-js validation rules:

https://github.com/graphql/graphql-js/tree/master/src/validation/rules
