### ISSUE TITLE
Use of postgraphql on digital ocean

### ISSUE THREAD

**Issue by cbjarnson** [calebmer/postgraphql#389]
This is kind of a newby question. I am trying to make an app to try this postgraphql thing out before trying it with a larger project. I am trying to use it by having it create an api for a web app( built with React and Apollo to work with GraphQL) and an ios and android app (built with React and Apollo). The app is a simple app for people to manage their collection of mini trains. 
![app](https://cloud.githubusercontent.com/assets/6126000/23721513/4878caf6-03ff-11e7-8660-3c501badcaf3.png)
So how do I set this up on digital ocean? I can get postgresql setup there, but how to install postgraphql, I don't know. I mostly do front end stuff and this setting up an api is confusing. Also is this even the right solution to use? Should I just use node.js and express to create the api? 
<img width="317" alt="screen shot 2017-01-23 at 3 17 25 pm" src="https://cloud.githubusercontent.com/assets/6126000/23721654/ce309160-03ff-11e7-8eb8-601dc2fbdc99.png">
<img width="317" alt="screen shot 2017-01-23 at 3 17 30 pm" src="https://cloud.githubusercontent.com/assets/6126000/23721655/ce32ea8c-03ff-11e7-8be2-4c1d4afab74b.png">
<img width="309" alt="screen shot 2017-01-23 at 3 17 35 pm" src="https://cloud.githubusercontent.com/assets/6126000/23721656/ce341a60-03ff-11e7-941f-ab15a20dcb0a.png">

**Comment by calebmer** [comment]
The process is very similar (if not identical) to deploying a Node.js app to Digital Ocean 😊

This is a good tutorial outlining the process in general for Node.js: https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04

Here’s an issue where some users share their experiencing using PM2 with PostGraphQL in production: https://github.com/calebmer/postgraphql/issues/82

It may be also useful for you to check out the PostGraphQL as a library documentation: https://github.com/calebmer/postgraphql/blob/master/docs/library.md

I hope this helps! Please let us know if you have any more questions, and good luck 😊
