### ISSUE TITLE
Passing value to stored function

### ISSUE THREAD

**Issue by TimJMartin** [calebmer/postgraphql#392]
Hi

I am just getting starting with GraphQL and Postgraphql so apologies for a novice question.

I have 12 tables, each have their own primary key, whilst they also have another value which models the one-to-many relationship. So looking at the documentation I wrote a stored function to return a set of results. However, how do I pass a value into that.

For example

```graphql
{
  postsByID(primary_key: "1") {
    primary_key
    id
    posts
    getCommentsByPostID(search: id) {
      edges {
        node {
          primary_key
          id
          comments
        }
      }
    }
  }
}
```

Because it is a one-to-many I cannot setup foreign keys as they are not unique.

Thanks for your help

**Comment by calebmer** [comment]
Take a look at the docs on procedures which show all of the different types of procedures PostGraphQL supports: https://github.com/calebmer/postgraphql/blob/master/docs/procedures.md

Does that help? If not could we see the SQL for the table and procedure you are using 😊

**Comment by TimJMartin** [comment]
So this is my stored function

```
create function search(postID bigint) returns setof comments as $$
  select *
  from comments
  where
    id = postID;
$$ language sql stable;
```

I have looked over that page and couldn't see a suitable example. 

So I need to search my posts table using the primary key, but then use the ID from that response to query my comments table.

Hope that makes sense?

Unfortunately it is not my data so am stuck with the data model just trying to get a good working example of GraphQL in action

**Comment by calebmer** [comment]
@TimJMartin 

That function should be query-able as:

```graphql
{
  search(postid: 5) {
    edges {
      node {
        # Comment fields...
      }
    }
  }
}
```

If you wanted to use that function as a computed column you could define it as:

```sql
create function post_search(post post) returns setof comments as $$
  select *
  from comments
  where
    id = post.id;
$$ language sql stable;
```

…and query like this:


```graphql
{
  postById(id: 5) {
    title
    search {
      edges {
        node {
          # Comment fields...
        }
      }
    }
  }
}
```

**Comment by TimJMartin** [comment]
@calebmer that works brilliantly. The only thing I couldn't get to work was have (post post) it kept saying post was not a type, so just had a single variable as the tablename
