### ISSUE TITLE
Views don't have primary keys

### ISSUE THREAD

**Issue by nbaum** [calebmer/postgraphql#4]
Making a GraphML schema for a PG schema containing views fails because views don't have primary keys.

**Comment by calebmer** [comment]
Yeah this is a big deal. Didn't think about that, thanks.

I decided to error when tables didn't have primary keys so to enforce support for the Relay `Node` interface, but views don't necessarily need to implement `Node`. I'll fix this soon.

**Comment by calebmer** [comment]
Fixed this in #10 if you want to try it out.

If you want, I've started a [Gitter room](https://gitter.im/calebmer/postgraphql) if you want to talk about your experiences with PostGraphQL. Also, if you'd like to contribute I want to adopt an open-open source governance model so core collaborators have direct commit rights on the repo (only makes sense as PostGraphQL is definitely a critical dependency).

**Comment by calebmer** [comment]
Closing as this is fixed in 1.1.0 🔥
