### ISSUE TITLE
JWT Token Verification using RS256

### ISSUE THREAD

**Issue by angelosarto** [calebmer/postgraphql#404]
I was having some problems getting token verification working if the token was signed using RS256 instead of HS256. 

In RS256 you need to pass in the public key in PEM format.   My issues was that the PEM format is strict both in terms of encoding (base64) AND  line breaking.

1.  Download your pem file it should like this
```
-----BEGIN CERTIFICATE-----
MIIC+DC...
...j+NjK0Bjo=
-----END CERTIFICATE-----
```
1. Your PEM file needs to have a line break after BEGIN CERTIFICATE---- and then a line break every 64 characters.   A quick way to do this on *nix/mac is this `fold filename.pem > filename-wrapped.pem`
1.  Since its pretty hard to pass things with line breaks you should set an environment variable from it like this. (this folds it automatically, if its already wrapped it will do nothing`
`export GRAPHQL_SECRET="$(cat filename.pem | fold -64)"`
1.  Then start up your graphql server passing `--secret=${GRAPHQL_SECRET}`

You still need to figure out how to pass audience until [this issue](https://github.com/calebmer/postgraphql/issues/292) closes

**Comment by benjie** [comment]
@angelosarto Nice auto-close to give documentation for others who may struggle in future 👍

**Comment by calebmer** [comment]
It’s really awesome to know RS256 works without any other modifications! Does signing work fine?

**Comment by benjie** [comment]
Thanks @natejenkins; I've modified the issue description with your fixes 👍

**Comment by yleigh** [comment]
> I was having some problems getting token verification working if the token was signed using RS256 instead of HS256.
> 
> In RS256 you need to pass in the public key in PEM format. My issues was that the PEM format is strict both in terms of encoding (base64) AND line breaking.
> 
> 1. Download your pem file it should like this
> 
> ```
> -----BEGIN CERTIFICATE-----
> MIIC+DC...
> ...j+NjK0Bjo=
> -----END CERTIFICATE-----
> ```
> 
> 1. Your PEM file needs to have a line break after BEGIN CERTIFICATE---- and then a line break every 64 characters.   A quick way to do this on *nix/mac is this `fold filename.pem > filename-wrapped.pem`
> 2. Since its pretty hard to pass things with line breaks you should set an environment variable from it like this. (this folds it automatically, if its already wrapped it will do nothing
>    `export GRAPHQL_SECRET="$(cat filename.pem | fold -64)"`
> 3. Then start up your graphql server passing `--jwt-secret="${GRAPHQL_SECRET}"`
> 
> You still need to figure out how to pass audience until [this issue](https://github.com/calebmer/postgraphql/issues/292) closes

Could you please explain how RS256 works in this case?
I'm using PostGraphile 4.6.0, has option set as:
`createServer(
    postgraphile(env.DATABASE_URL, "public", {
      jwtSecret: "./publickey.pem",
      jwtVerifyAlgorithms: ["RS256"],
      jwtPgTypeIdentifier: "public.jwt_token",
      graphiql: true,
      enhanceGraphiql: true,
      graphqlRoute: env.POSTGRAPHILE_ROUTE + "/graphql",
      graphiqlRoute: env.POSTGRAPHILE_ROUTE + "/graphiql",
    })
  ).listen(port, () => {
    console.log("Listening at port:" + port);
  });`
But when I sending the Authorization header in Postman with RS256 encrypted JWT token, always get 'errors: invalid algorithm'.
In fact, the JWT token I get back from this PostGraphile server is always HS256 encrypted.
Appears that RS256 doesn't take effect.
Could you show your working example of PostGraphile JWT verification with RS256?

**Comment by benjie** [comment]
It is treating the literal string you have passed it as the secret, as the secret. Same as it would if you passed it “MY_SECRET_HERE”. You need to read the file and send through the file contents.
