### ISSUE TITLE
Subscriptions example

### ISSUE THREAD

**Issue by giacomorebonato** [calebmer/postgraphql#45]
Where can I find a sample implementation of subscriptions?  
In the GraphQL blog it is too much theoretical... at least for my preparation.

Cheers.

**Comment by hardchor** [comment]
Hey @giacomorebonato 

Subscriptions are still in the very early stages, and you're right - there isn't a lot of documentation around them.

I suppose you'd like to use them as a real-time API? There's a few steps necessary to achieve that:

* trigger a `NOTIFY` command in postgres on `INSERT`/`UPDATE`/`DELETE`
* attach some kind of listener (e.g. `pg-pubsub` or `pgsql-listen-exchange` (via RabbitMQ))
* create a Websocket server that handles subscriptions and updates

As you can see, that goes over and above the scope of this project. If you decide to go down that route, I'd be curious as to what your experiences are.

**Comment by calebmer** [comment]
You can also follow https://github.com/facebook/graphql/pull/109 which is the unmerged spec to the GraphQL language supporting subscriptions 😊

**Comment by babakness** [comment]
Subscriptions have merged https://github.com/facebook/graphql/pull/267
