### ISSUE TITLE
Disable auto updatable views

### ISSUE THREAD

**Issue by pvdvreede** [calebmer/postgraphql#51]
Hey there,

I am playing with postgraphql with one of our current schemas and noticed that if i create a view to a table in another schema it also generates the mutations for that view.

I would prefer it not to show those mutations, and have tried creating rules set to `DO NOTHING` for the view, but the graphql introspection is still showing the mutations. 

Is there a way to tell postgraphql to not generate mutations for particular views?

**Comment by pvdvreede** [comment]
It also looks like the associations between two tables does not come through in the views. Is there a way to get postgraphql to see an association between two views?

I would like to be able to manually tweak how the tables are exposed through to graphql so that the underlying table structure is abstracted away. This way I can show domain objects rather than normalised db table objects.

**Comment by calebmer** [comment]
As I mentioned in #53, I feel like the best solution is to detect granted access levels of the role used at schema creation time. If that role doesn’t have access to update an auto updatable view, we can hide that from our mutations list.

**Comment by calebmer** [comment]
Released in `1.7.0` 🎉
