### ISSUE TITLE
Schema changes

### ISSUE THREAD

**Issue by d-winter** [calebmer/postgraphql#54]
Hi,
currently it seems that I have to restart the postgraphql server when the schema changes.
This will be often the case in my current project. Is there any way to tell the postgraphql process to rescan the schema without restarting it? This would be absolutely awesome.
Thanks for any tips and this awesome project!
Daniel

**Comment by burkhardr** [comment]
Hey @d-winter . This isn't necessarily postgraphql-specific, but you can easily achieve the same result yourself with nodemon:

```bash
npm i -g nodemon
nodemon -w path/to/schema -x "postgraphql postgres://localhost:5432/mydb --schema forum --development"
```

**Comment by d-winter** [comment]
Hey, 
thanks for this approach. My problem is, that the db runs on another machine so I can't watch the schema file with nodemon.

**Comment by calebmer** [comment]
You might try adding [triggers](https://www.postgresql.org/docs/current/static/sql-createtrigger.html) to `pg_catalog` tables and emit notifications with [`NOTIFY`](https://www.postgresql.org/docs/current/static/sql-notify.html) which can be consumed by a monitor process.

I'm not sure how common a scenario this is so I'm hesitant to add it to PostGraphQL. Also there are performance implications if we are updating the in-memory schema often.

**Comment by d-winter** [comment]
Ok, thanks. I think I will check how I implemented an automatic rescan using a trigger.
Thanks a lot for your time!
