### ISSUE TITLE
Querying null or not null values

### ISSUE THREAD

**Issue by xleliberty** [calebmer/postgraphql#59]
Hi, 
we are evaluating this awesome piece of software ! And it looks really amazing, thank you very much!

I'd like to know if there is a way to query null or not null values.

Something like: 
````

{
	myTestQuery(paramOne: "paramOneValue") {
		totalCount
		nodes {
			consumerCategories(orderBy: position, deletedAt: !null) {
				nodes: {
					rowId
					name
				}
			}
		}
	}
}
```

Thanks 

Xavier

**Comment by calebmer** [comment]
Not currently, we are looking at ways to improve our free form filtering if you want to comment/contribute in #47.

However, this *can* be done using a procedure in the meantime. Something like:

```sql
create function person_undeleted_categories(person person) returns setof categories …
```

See the [docs](https://github.com/calebmer/postgraphql/blob/master/docs/procedures.md) on procedures for more 😊

**Comment by xleliberty** [comment]
Thanks for your reply, 
yes we will contribuate on #47

**Comment by calebmer** [comment]
Thanks! 😊
