### ISSUE TITLE
Importing `createGraphqlSchema` does not result in a promisified version of node-postgres

### ISSUE THREAD

**Issue by ferdinandsalis** [calebmer/postgraphql#69]
While working on relay-example I wanted to use `createGraphqlSchema` so I can create a `schema.json` file that `babel-relay-plugin` needs to transpile the relay queries. However this results in an error because the `node-postgres` has not been promisified yet.

**Comment by calebmer** [comment]
Could you give me exact code to reproduce?

**Comment by calebmer** [comment]
Look at [this](https://github.com/calebmer/postgraphql/commit/6f9d1b0797ca799baf94ce44fa558672e87ecf7c) commit/test case. Would that fix it for you?

**Comment by calebmer** [comment]
If that doesn’t work, `pg` version 5.1.0 has support for promises! So we should probably migrate to that away from `bluebird`.

**Comment by ferdinandsalis** [comment]
I am actually not doing this anymore (see [this](https://github.com/calebmer/postgraphql/blob/feat/relay-example/examples/forum-relay/scripts/updateSchema.js)). Though I think it should still work. I will test it and let you know if the error still occurs.

**Comment by ferdinandsalis** [comment]
I can confirm that this fixes the problem. Thanks.

**Comment by ferdinandsalis** [comment]
Closing this as this is fixed in 2.0.0
