### ISSUE TITLE
Version check returning undefined

### ISSUE THREAD

**Issue by tryggvigy** [calebmer/postgraphql#7]
![image](https://cloud.githubusercontent.com/assets/2373958/14869094/cc9d4122-0cc0-11e6-856e-61bd5fd64055.png)

Could this be due to 
line 14 in main.js `const manifest = readFileSync(path.resolve(__dirname, '../package.json'))`
causing `.version(manifest.version)` to fail?

**Comment by calebmer** [comment]
You got it, thanks for the catch 👍

I opened a room in Gitter if you want to talk about your experiences with PostGraphQL: https://gitter.im/calebmer/postgraphql

**Comment by tryggvigy** [comment]
Awesome!
