### ISSUE TITLE
Dockefile for deployment as a container?

### ISSUE THREAD

**Issue by Jimexist** [calebmer/postgraphql#75]
Is there a plan? Thanks.

By the way i saw [this](https://hub.docker.com/r/pvdvreede/postgraphql/tags/) but not quite sure how it's related to this repo.

**Comment by pvdvreede** [comment]
I don't think there is an official docker image for postgraphql.

You can see #52 which has a docker-compose file for development.

If you wanted to create your own docker image to deploy postgraphql then you could probably get away with something as simple as:

```dockerfile
FROM node:5
RUN npm install -g postgraphql
EXPOSE 3000
ENV PORT 3000
ENTRYPOINT ["postgraphql", "-n", "0.0.0.0", "-p", "3000"]
```

I havent tested that, but something along those lines should work.

**Comment by pvdvreede** [comment]
That link to docker hub you have is mine - Im not quite sure when I did that, but I think you would be better off having your own dockerfile with the above as I dont maintain that particular docker image, so it wont have the latest version of postgraphql.

**Comment by pvdvreede** [comment]
Hi @Jimexist were you able to setup your docker image with the above info alright?

**Comment by Jimexist** [comment]
Yeah I can build an image out of that `Dockerfile`, haven't tested in production yet, tho.
Thanks!

**Comment by pvdvreede** [comment]
Good to hear, I'll close this issue then, but feel free to open one if you have anymore problems. :smile:
