### ISSUE TITLE
Multiple databases support

### ISSUE THREAD

**Issue by msaron** [calebmer/postgraphql#77]
Is there anyway to support multiple databases? Because of customer security concerns, we have one database per customer with each database having the same schema as the others. When a customer logins in, they enter three pieces of information: database name, username, and password. After they login, they are automatically linked to the database they specified (user authentication information is stored inside the database they specified). For enterprise customers, this is very important. Also it helps us scale the database for larger customers and if one database goes down, the others are not affected.

**Comment by calebmer** [comment]
This is an interesting usecase, and one that PostGraphQL could be used for. PostGraphQL likely would not support such a feature (although PostgreSQL does see [Foreign Tables](https://www.postgresql.org/docs/9.1/static/sql-createforeigntable.html) as it would add a lot of complexity for a niche use case.

I would recommend looking into PostgreSQL [Foreign Tables](https://www.postgresql.org/docs/9.1/static/sql-createforeigntable.html), or consider running a single PostGraphQL instance for every database instance. The isolation could be helpful.

**Comment by msaron** [comment]
I don't think that would work. Currently we are using one database for all clients using Python Pyramid. We are moving the app to React. We are following the advice from the following blog [https://securedb.co/blog/multi-tenant-saas-with-postgresql/](url). It makes a lot of sense from the problems we have had, because some of our customers are large and some are small.

We will probably clone your app and then modify it to connect to the user based on the database identified in the JWT.
