### ISSUE TITLE
password authentication failed for user

### ISSUE THREAD

**Issue by tim-field** [calebmer/postgraphql#80]
I expect that this is user error, I'm new to PostGress, so apologies in advance.

```
tim~> psql books
psql (9.5.3)
Type "help" for help.

books=# select * from author;
 id | first_name | last_name 
----+------------+-----------
  1 | Tom        | McCarthy
(1 row)

books=# \q
tim~>postgraphql postgres://localhost:5432/books --development
GraphQL server listening at http://localhost:3000/ 🚀
```

So far so good, postgess is running on port 5432.  I can also connect fine with pgAdmin
But any attempts to use the service result in 
```
{
  "errors": [
    {
      "message": "password authentication failed for user \"tim\""
    }
  ]
}
```

Any clues would be appreciated

**Comment by tim-field** [comment]
So connecting with postgres://tim:xxx@localhost:5432/books works... so as suspected I'm doing something wrong. Not an issue with postgraphql. I'll close this, but if you feel like sharing a better way to connect I'm all ears :)

**Comment by calebmer** [comment]
Glad you figured it out 😊
