### ISSUE TITLE
Doesn't work with `interval` field

### ISSUE THREAD

**Issue by owais** [calebmer/postgraphql#88]
One of my databases has a table that contains an `interval` field and postgraphql doesn't work with the DB. Any request to any table returns the following error (assuming the table `myTable` has an interval field called `duration`):

```json
{
  "errors": [
    {
      "message": "Query.myTableNodes(duration:) argument type must be Input Type but got: Interval."
    }
  ]
}
```

**Comment by calebmer** [comment]
Thanks so much for reporting this, a fix has been published in `1.8.1` :tada: :+1:
