### ISSUE TITLE
Use pg-range library

### ISSUE THREAD

**Issue by langpavel** [calebmer/postgraphql#90]
Use `pg-range` ([npm](https://www.npmjs.com/package/pg-range), [GitHub](https://github.com/WhoopInc/node-pg-range)) library for `int4range`, `int8range`, `numrange`, `tsrange`, `tstzrange`, `daterange` types

**Comment by calebmer** [comment]
I’m going to close this as its in the PostGraphQL 2.0 beta 🎉 

Specifically range types are turned into the following format (using `daterange` as an example):

```graphql
type DateRange {
  start: DateRangeBound
  end: DateRangeBound
}

type DateRangeBound {
  value: Date!
  inclusive: Bool!
}
```

Start playing with the pre-release, the final release should be out really soon. Tell me what you think! :+1:

```
npm install -g postgraphql@next
postgraphql
```
