### ISSUE TITLE
Queries cannot run in parallel?

### ISSUE THREAD

**Issue by langpavel** [calebmer/postgraphql#94]
I extracted code from PostGraphQL and create express middleware.
I observed that when two queries are run in parallel, postgraphql freezes.
When I run postgraphql from commandline, it looks like execution of second query is blocked until first finishes. What is wrong?

My middleware code:

```jsx
import Promise from 'bluebird';
import pg, { Client } from 'pg';
import onFinished from 'on-finished';
import expressGraphql from 'express-graphql';
import { createGraphqlSchema } from 'postgraphql';
import { pgConnectionString } from '../config.js';

Promise.promisifyAll(pg);
Promise.promisifyAll(Client);

let graphqlSchema = null;
const createSchemaPromise = async () => {
  graphqlSchema = await createGraphqlSchema(pgConnectionString, 'public');
  return graphqlSchema;
};

export default function register(app) {
  app.all('/admin/graphql', expressGraphql(async req => {
    // TODO: SECURITY - Protect this route

    // Acquire a new client for every request.
    const client = await pg.connectAsync(pgConnectionString);

    // Start a transaction for our client and set it up.
    await client.queryAsync('begin');

    // Make sure we release our client back to the pool once the response has
    // finished.
    onFinished(req.res, async () => {
      // Try to end our session with a commit. If it succeeds, release the
      // client back into the pool. If it fails, release the client back into
      // the pool, but also report that it failed. We cannot report an error in
      // the request at this point because it has finished.
      try {
        await client.queryAsync('commit');
        client.end();
      } catch (err) {
        console.error(err.message); // eslint-disable-line no-console
        client.end(err);
      }
    });

    return {
      // Await the `graphqlSchema` because it may be a promise.
      schema: graphqlSchema || await createSchemaPromise(),
      context: { client },
      pretty: true,
      graphiql: true,
    };
  }));
}
```

**Comment by calebmer** [comment]
Hi @langpavel, have you read [Using PostGraphQL as a Library](https://github.com/calebmer/postgraphql/blob/master/docs/library.md)? Currently you are able to configure and use PostGraphQL as Express or Connect middleware. If there are features you’d like to remove (as I see you’ve removed authentication) let me know and we’ll see if we can incorporate it up stream.

I’m not sure why exactly you’re getting blocked, but I do see something that looks wrong.

Here:

```js
return {
  // Await the `graphqlSchema` because it may be a promise.
  schema: graphqlSchema || await createSchemaPromise(),
  context: { client },
  pretty: true,
  graphiql: true,
};
```

You’re calling a function that you define above, here:

```js
let graphqlSchema = null;
const createSchemaPromise = async () => {
  graphqlSchema = await createGraphqlSchema(pgConnectionString, 'public');
  return graphqlSchema;
};
```

If you call PostGraphQL twice in quick succession, you may call `createSchemaPromise` twice creating a race condition and likely the odd behavior you’re experiencing.

I’d recommend using the `postgraphql` middleware. If it’s missing some things, let’s talk about them and add those features in.

**Comment by langpavel** [comment]
Hi, thanks for response!

> Have you read Using PostGraphQL as a Library?

No, can you please add a link to README.md? :-) I totally overlooked this...

> If you call PostGraphQL twice in quick succession, you may call createSchemaPromise twice creating a race condition and likely the odd behavior you’re experiencing.

Ahh you are right! But this race condition can occur only after very first runs and I'm getting blocked after some time after that...

**Comment by langpavel** [comment]
Hi @calebmer 

I followed [Using PostGraphQL as a Library](https://github.com/calebmer/postgraphql/blob/master/docs/library.md) and succesfully setup it as express middleware, but freezing still occurs when I run single query more times with little delay (hitting Ctrl+Enter multiple times)

After multiple requests sent, middleware stuck and even GraphiQL does not loads. all subsequent queries reaching PostGraphQL endpoint ends with timeout (even GET for GraphiQL)

**Comment by calebmer** [comment]
Hi @langpavel, did you end up solving the issue? And out of curiosity how? 😊

**Comment by langpavel** [comment]
@calebmer Just as you say :-)

```jsx
import postgraphql from 'postgraphql';
import { pgConnectionString } from '../config.js';

export default function register(app) {
  // TODO: SECURE
  app.use('/admin/graphql', postgraphql(pgConnectionString, 'public', {
    development: true,
    log: true,
  }));
}
```
