### ISSUE TITLE
Using postgraphql with AWS Lambda?

### ISSUE THREAD

**Issue by marclar** [calebmer/postgraphql#96]
I'm working on a project using the [Serverless](http://serverless.com/) framework, and I'm wondering how to integrate with postgraphql.

There's really no "booting up" for each Lambda, so it's not like I'd use PM2 to keep postgraphql running. The lifecycle would be more like, 

1. Lambda starts upon receiving an HTTP request from API Gateway
1. Pull out necessary data from header or body
1. Invoke postgraphql with this data
1. Call callback with the results from postgraphql

Any pointers?

Thanks!

**Comment by calebmer** [comment]
This is an interesting case. PostGraphQL needs a “boot” step currently to introspect a PostgreSQL schema, so it can’t currently be run statelessly. However, in the future, we’re moving to a [single SQL query approach](https://github.com/calebmer/postgraphql/blob/next/queries/introspection-query.sql) to introspecting PostgreSQL. At that point the inspection result is just data and not some awkward form that isn’t easily serializable. In the future then we may be able to do the following (either through bash like below or an equivalent Node.js API):

```bash
postgraphql file://path/to/schema/file.json
```

(vs `postgraphql postgres://localhost:5432…`)

There will always be some startup tax as we generate the appropriate GraphQL objects, however. Whether this is more or less then the startup tax from calling `new GraphQLObjectType` yourself is yet to be seen.

I’ve yet to play around more with Serverless and Lambda, but I love the idea of GraphQL cloud “functions.” However, I’m not sure if I’d recommend PostGraphQL for a cloud function model or any other app that needs to do some housekeeping on start.

**Comment by marclar** [comment]
Hm. I think it might be reasonable to periodically cache our schema in a static `*.json` file. 

If we were to do this in a fork of PostGraphQL, can you point out where I could substitute this file in place of the introspection query?

(Or are you saying that it's not easily serializable and wouldn't really be an option until you move to the single SQL query approach?)

Thanks for your help, @calebmer

**Comment by calebmer** [comment]
It probably can’t be serialized easily until we move to the single query approach. It’s likely *possible* though if you want to give it a shot. Check out the two files [`getCatalog.js`](https://github.com/calebmer/postgraphql/blob/dc4a97088037ae75f791aec68e9d71ffb4bf49f7/src/postgres/getCatalog.js) and more importantly to you [`catalog.js`](https://github.com/calebmer/postgraphql/blob/dc4a97088037ae75f791aec68e9d71ffb4bf49f7/src/postgres/catalog.js) (the latter is what you’d want to serialize).

**Comment by marclar** [comment]
Cool -- thank you. Will take a look.

**Comment by javatask** [comment]
Where can I get details to use postgraphql with AWS Lambda?

**Comment by calebmer** [comment]
@javatask with the PostGraphQL 2.0 upgrade, this should be a lot easier, but would require a PR. All that would be involved is running [the introspection SQL query](https://github.com/calebmer/postgraphql/blob/ea3c94de6bbef483c70a3f15f3792b539f943b96/resources/introspection-query.sql) beforehand and construct a [`PgCatalog` from that](https://github.com/calebmer/postgraphql/blob/c752260666f2a9a2b9f5f40916bc1b2348b28f42/src/postgraphql/schema/createPostGraphQLSchema.ts#L35) replacing the code [where we connect a Postgres client to run the introspection](https://github.com/calebmer/postgraphql/blob/c752260666f2a9a2b9f5f40916bc1b2348b28f42/src/postgraphql/schema/createPostGraphQLSchema.ts#L37-L48).

**Comment by javatask** [comment]
Thanks! 
I'll try and will write article on medium

**Comment by rentrop** [comment]
@javatask, @marclar any updates? Did you manage to do it?

**Comment by tianhuil** [comment]
@rentrop: here's an example of Postgraphile running on AWS Lambda: https://github.com/graphile/postgraphile-lambda-example
